/*   Automatically generated by Iup 3.0 LED Compiler to C.   */

#include <stdlib.h>
#include <stdarg.h>
#include <iup.h>

static Ihandle* named[     13 ];


void simple_loadled (void)
{
  named[0] = IupSetAtt( "mnOpen", IupMenu(
    IupItem( "CGM - Binary", "SimplePlayCGMBin" ),
    IupItem( "CGM - Text", "SimplePlayCGMText" ),
    IupItem( "METAFILE", "SimplePlayMetafile" ),
    IupItem( "WMF", "SimplePlayWMF" ),
    IupItem( "EMF", "SimplePlayEMF" ),
  NULL), NULL );
  named[1] = IupSetAtt( "mnSaveAs", IupMenu(
    IupItem( "DEBUG", "SimpleDrawDebug" ),
    IupItem( "CGM - Binary", "SimpleDrawCGMBin" ),
    IupItem( "CGM - Text", "SimpleDrawCGMText" ),
    IupItem( "DGN", "SimpleDrawDGN" ),
    IupItem( "DXF", "SimpleDrawDXF" ),
    IupItem( "EMF", "SimpleDrawEMF" ),
    IupItem( "METAFILE", "SimpleDrawMetafile" ),
    IupItem( "PDF", "SimpleDrawPDF" ),
    IupItem( "PS", "SimpleDrawPS" ),
    IupItem( "EPS", "SimpleDrawEPS" ),
    IupItem( "SVG", "SimpleDrawSVG" ),
    IupItem( "WMF", "SimpleDrawWMF" ),
  NULL), NULL );
  named[2] = IupSetAtt( "mnFile", IupMenu(
    IupSubmenu( "Open",
      named[0] /* mnOpen */
    ),
    IupSubmenu( "Save As",
      named[1] /* mnSaveAs */
    ),
    IupSeparator(),
    IupItem( "Print", "SimpleDrawPrint" ),
    IupItem( "Print Dialog...", "SimpleDrawPrintDialog" ),
    IupSeparator(),
    IupItem( "Exit", "cmdExit" ),
  NULL), NULL );
  named[3] = IupSetAtt( "mnEdit", IupMenu(
    IupItem( "Copy as Metafile", "SimpleDrawClipboardMetafile" ),
    IupItem( "Copy as EMF", "SimpleDrawClipboardEMF" ),
    IupItem( "Copy as Bitmap", "SimpleDrawClipboardBitmap" ),
    IupItem( "Paste", "SimplePlayClipboard" ),
  NULL), NULL );
  named[4] = IupSetAtt( "mnClipping", IupMenu(
    IupItem( "Off", "SimpleClippingOff" ),
    IupItem( "Area", "SimpleClippingArea" ),
    IupItem( "Polygon", "SimpleClippingPolygon" ),
    IupItem( "Region", "SimpleClippingRegion" ),
  NULL), NULL );
  named[5] = IupSetAtt( "mnWriteMode", IupMenu(
    IupItem( "Replace", "SimpleReplace" ),
    IupItem( "Xor", "SimpleXor" ),
    IupItem( "Not Xor", "SimpleNotXor" ),
  NULL), NULL );
  named[6] = IupSetAtt( "mnOptions", IupMenu(
    IupSubmenu( "Clipping",
      named[4] /* mnClipping */
    ),
    IupSubmenu( "Write Mode",
      named[5] /* mnWriteMode */
    ),
    IupItem( "Simulate", "SimpleDrawSimulate" ),
    IupItem( "Transform", "SimpleTransform" ),
    IupItem( "Context Plus", "SimpleContextPlus" ),
  NULL), NULL );
  named[7] = IupSetAtt( "mnSurface", IupMenu(
    IupItem( "Window", "SimpleDrawWindow" ),
    IupItem( "Server Image", "SimpleDrawImage" ),
    IupItem( "Image RGB", "SimpleDrawImageRGB" ),
    IupItem( "OpenGL", "SimpleDrawGL" ),
  NULL), NULL );
  named[8] = IupSetAtt( "mnPrimitives", IupMenu(
    IupItem( "All", "SimpleAll" ),
    IupItem( "Text Align", "SimpleTextAlign" ),
    IupItem( "Text Fonts", "SimpleTextFonts" ),
    IupItem( "Test", "SimpleTest" ),
  NULL), NULL );
  named[9] = IupSetAtt( "mnSimpleMenu", IupMenu(
    IupSubmenu( "File",
      named[2] /* mnFile */
    ),
    IupSubmenu( "Edit",
      named[3] /* mnEdit */
    ),
    IupSubmenu( "Options",
      named[6] /* mnOptions */
    ),
    IupSubmenu( "Surface",
      named[7] /* mnSurface */
    ),
    IupSubmenu( "Primitives",
      named[8] /* mnPrimitives */
    ),
  NULL), NULL );
  named[10] = IupSetAtt( "SimpleCanvas", IupCanvas( "SimpleRepaint" ), 
    "BORDER", "0", NULL );
  named[11] = IupSetAtt( "SimpleDialog", IupDialog(
    named[10] /* SimpleCanvas */
  ), 
    "TITLE", "Simple Draw", 
    "MENU", "mnSimpleMenu", NULL );
}
