#ifndef _BPARSE_H_
#define _BPARSE_H_

typedef int(*_cdcgmsizecb)(cdCanvas* canvas, int w, int h, double w_mm, double h_mm);
typedef int(*_cdcgmbegmtfcb)(cdCanvas* canvas, int *xmin, int *ymin, int *xmax, int *ymax);
typedef int(*_cdcgmcountercb)(cdCanvas* canvas, double size);
typedef int(*_cdcgmsclmdecb)(cdCanvas* canvas, short scl_mde, short *drw_mode, double *factor);
typedef int(*_cdcgmvdcextcb)(cdCanvas* canvas, short type, double *xmn, double *ymn, double *xmx, double *ymx);
typedef int(*_cdcgmbegpictcb)(cdCanvas* canvas , char *pict );
typedef int(*_cdcgmbegpictbcb)(cdCanvas* canvas, double scale_x, double scale_y, 
                               double vdc_x2pix, double vdc_y2pix,
                               double vdc_x2mm, double vdc_y2mm, int drw_mode, 
                               double xmin, double ymin, double xmax, double ymax);

extern _cdcgmsizecb cdcgmsizecb;
extern _cdcgmbegmtfcb cdcgmbegmtfcb;
extern _cdcgmcountercb cdcgmcountercb;
extern _cdcgmsclmdecb cdcgmsclmdecb;
extern _cdcgmvdcextcb cdcgmvdcextcb;
extern _cdcgmbegpictcb cdcgmbegpictcb;
extern _cdcgmbegpictbcb cdcgmbegpictbcb;

int cgmb_noop ( void );
int cgmb_begmtf ( void );
int cgmb_endmtf ( void );
int cgmb_begpic ( void );
int cgmb_begpib ( void );
int cgmb_endpic ( void );
int cgmb_mtfver ( void );
int cgmb_mtfdsc ( void );
int cgmb_vdctyp ( void );
int cgmb_intpre ( void );
int cgmb_realpr ( void );
int cgmb_indpre ( void );
int cgmb_colpre ( void );
int cgmb_colipr ( void );
int cgmb_maxcoi ( void );
int cgmb_covaex ( void );
int cgmb_mtfell ( void );
int cgmb_bmtfdf ( void );
int cgmb_fntlst ( void );
int cgmb_chslst ( void );
int cgmb_chcdac ( void );
int cgmb_sclmde ( void );
int cgmb_clslmd ( void );
int cgmb_lnwdmd ( void );
int cgmb_mkszmd ( void );
int cgmb_edwdmd ( void );
int cgmb_vdcext ( void );
int cgmb_bckcol ( void );
int cgmb_vdcipr ( void );
int cgmb_vdcrpr ( void );
int cgmb_auxcol ( void );
int cgmb_transp ( void );
int cgmb_clprec ( void );
int cgmb_clpind ( void );
int cgmb_polyln ( void );
int cgmb_djtply ( void );
int cgmb_polymk ( void );
int cgmb_text ( void );
int cgmb_rsttxt ( void );
int cgmb_apdtxt ( void );
int cgmb_polygn ( void );
int cgmb_plgset ( void );
int cgmb_cellar ( void );
int cgm_generalized_drawing_primitive_4 ( void );
int cgm_generalized_drawing_primitive_5 ( void );
int cgmb_gdp ( void );
int cgmb_rect ( void );
int cgmb_circle ( void );
int cgmb_circ3p ( void );
int cgmb_cir3pc ( void );
int cgmb_circnt ( void );
int cgmb_ccntcl ( void );
int cgmb_ellips ( void );
int cgmb_ellarc ( void );
int cgmb_ellacl ( void );
int cgmb_lnbdin ( void );
int cgmb_lntype ( void );
int cgmb_lnwidt ( void );
int cgmb_lncolr ( void );
int cgmb_mkbdin ( void );
int cgmb_mktype ( void );
int cgmb_mksize ( void );
int cgmb_mkcolr ( void );
int cgmb_txbdin ( void );
int cgmb_txftin ( void );
int cgmb_txtprc ( void );
int cgmb_chrexp ( void );
int cgmb_chrspc ( void );
int cgmb_txtclr ( void );
int cgmb_chrhgt ( void );
int cgmb_chrori ( void );
int cgmb_txtpat ( void );
int cgmb_txtali ( void );
int cgmb_chseti ( void );
int cgmb_achsti ( void );
int cgmb_fillin ( void );
int cgmb_intsty ( void );
int cgmb_fillco ( void );
int cgmb_hatind ( void );
int cgmb_patind ( void );
int cgmb_edgind ( void );
int cgmb_edgtyp ( void );
int cgmb_edgwid ( void );
int cgmb_edgcol ( void );
int cgmb_edgvis ( void );
int cgmb_fillrf ( void );
int cgmb_pattab ( void );
int cgmb_messag ( void );
int cgmb_appdta ( void );
int cgmb_patsiz ( void );
int cgmb_coltab ( void );
int cgmb_asf ( void );
int cgmb_escape ( void );

#endif
