int cgm_do_vdcext ( tpoint, tpoint );
int cgm_do_bckcol ( trgb );
int cgm_do_transp ( int );
int cgm_do_clprec ( tpoint, tpoint );
int cgm_do_clpind ( int );
int cgm_do_polyln ( int, tpoint * );
int cgm_do_incply ( int, tpoint * );
int cgm_do_djtply ( int, tpoint * );
int cgm_do_indpl ( int, tpoint * );
int cgm_do_polymk ( int, tpoint * );
int cgm_do_incplm ( int, tpoint * );
int cgm_do_text ( int, char *, tpoint );
int cgm_do_txtalign ( int hor, int ver );
int cgm_do_polygn ( int, tpoint * );
int cgm_do_incplg ( int, tpoint * );
int cgm_do_plgset( int, int, tpoint *, short * );
int cgm_do_cellar ( tpoint, tpoint, tpoint, int, int, long, tcolor * );
int cgm_do_gdp ( int, tpoint *, char * );
int cgm_do_rect ( tpoint point1, tpoint point2 );
int cgm_do_circle ( tpoint, double );
int cgm_do_circ3p ( tpoint, tpoint, tpoint );
int cgm_do_circ3pc ( tpoint, tpoint, tpoint, int );
int cgm_do_circcnt ( tpoint, tpoint, tpoint, double );
int cgm_do_ccntcl ( tpoint, tpoint, tpoint, double, int );
int cgm_do_ellips ( tpoint, tpoint, tpoint );
int cgm_do_ellarc ( tpoint, tpoint, tpoint, tpoint, tpoint );
int cgm_do_ellacl ( tpoint, tpoint, tpoint, tpoint, tpoint, int );
int cgm_do_text_height ( double );
