
#include "lua.h"
extern void wetgenes_cache_preloader(lua_State *L);
extern int luaopen_profiler(lua_State *L);
extern int luaopen_wetgenes_pack_core(lua_State *L);
extern int luaopen_zip(lua_State *L);
extern int luaopen_zlib(lua_State *L);
extern int luaopen_wetgenes_freetype_core(lua_State *L);
extern int luaopen_bit(lua_State *L);
extern int luaopen_wetgenes_ogg_core(lua_State *L);
extern int luaopen_al_core(lua_State *L);
extern int luaopen_alc_core(lua_State *L);
extern int luaopen_wetgenes_tardis_core(lua_State *L);
extern int luaopen_gles_core(lua_State *L);
extern int luaopen_wetgenes_grd_core(lua_State *L);
extern int luaopen_wetgenes_grdmap_core(lua_State *L);
extern int luaopen_wetgenes_sod_core(lua_State *L);
extern int luaopen_wetgenes_speak_core(lua_State *L);
extern int luaopen_lash(lua_State *L);
extern int luaopen_lfs(lua_State *L);
extern int luaopen_socket_core(lua_State *L);
extern int luaopen_mime_core(lua_State *L);
extern int luaopen_lsqlite3(lua_State *L);
extern int luaopen_lanes(lua_State *L);
extern int luaopen_posix_c(lua_State *L);
extern int luaopen_wetgenes_gamecake_core(lua_State *L);
extern int luaopen_wetgenes_win_core(lua_State *L);
extern int luaopen_wetgenes_win_linux_core(lua_State *L);

extern void lua_preloadlibs(lua_State *L)
{
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");
    lua_pushliteral(L, "profiler");
    lua_pushcfunction(L, luaopen_profiler);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.pack.core");
    lua_pushcfunction(L, luaopen_wetgenes_pack_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "zip");
    lua_pushcfunction(L, luaopen_zip);
    lua_settable(L, -3);
    lua_pushliteral(L, "zlib");
    lua_pushcfunction(L, luaopen_zlib);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.freetype.core");
    lua_pushcfunction(L, luaopen_wetgenes_freetype_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "bit");
    lua_pushcfunction(L, luaopen_bit);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.ogg.core");
    lua_pushcfunction(L, luaopen_wetgenes_ogg_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "al.core");
    lua_pushcfunction(L, luaopen_al_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "alc.core");
    lua_pushcfunction(L, luaopen_alc_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.tardis.core");
    lua_pushcfunction(L, luaopen_wetgenes_tardis_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "gles.core");
    lua_pushcfunction(L, luaopen_gles_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.grd.core");
    lua_pushcfunction(L, luaopen_wetgenes_grd_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.grdmap.core");
    lua_pushcfunction(L, luaopen_wetgenes_grdmap_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.sod.core");
    lua_pushcfunction(L, luaopen_wetgenes_sod_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.speak.core");
    lua_pushcfunction(L, luaopen_wetgenes_speak_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "lash");
    lua_pushcfunction(L, luaopen_lash);
    lua_settable(L, -3);
    lua_pushliteral(L, "lfs");
    lua_pushcfunction(L, luaopen_lfs);
    lua_settable(L, -3);
    lua_pushliteral(L, "socket.core");
    lua_pushcfunction(L, luaopen_socket_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "mime.core");
    lua_pushcfunction(L, luaopen_mime_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "sqlite");
    lua_pushcfunction(L, luaopen_lsqlite3);
    lua_settable(L, -3);
    lua_pushliteral(L, "lua51-lanes");
    lua_pushcfunction(L, luaopen_lanes);
    lua_settable(L, -3);
    lua_pushliteral(L, "posix_c");
    lua_pushcfunction(L, luaopen_posix_c);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.gamecake.core");
    lua_pushcfunction(L, luaopen_wetgenes_gamecake_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.win.core");
    lua_pushcfunction(L, luaopen_wetgenes_win_core);
    lua_settable(L, -3);
    lua_pushliteral(L, "wetgenes.win.linux.core");
    lua_pushcfunction(L, luaopen_wetgenes_win_linux_core);
    lua_settable(L, -3);
    lua_pop(L, 2);
	wetgenes_cache_preloader(L); // include embeded strings loader
}

