/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wetgenes_Bulb_Bulb */

#ifndef _Included_com_wetgenes_Bulb_Bulb
#define _Included_com_wetgenes_Bulb_Bulb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    setup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_setup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_start
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_clean
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    updatedraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_updatedraw
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    press
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_press
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_wetgenes_Bulb_Bulb
 * Method:    touch
 * Signature: (FFII)V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Bulb_Bulb_touch
  (JNIEnv *, jclass, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
