/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wetgenes_Yarn */

#ifndef _Included_com_wetgenes_Yarn
#define _Included_com_wetgenes_Yarn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wetgenes_Yarn
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Yarn_setup
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Yarn
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Yarn_clean
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Yarn
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Yarn_update
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Yarn
 * Method:    draw
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Yarn_draw
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_wetgenes_Yarn
 * Method:    getstring
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wetgenes_Yarn_getstring
  (JNIEnv *, jclass);

/*
 * Class:     com_wetgenes_Yarn
 * Method:    keypress
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wetgenes_Yarn_keypress
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
