/*   Automatically generated by Iup 3.0 LED Compiler to C.   */

#include <stdlib.h>
#include <stdarg.h>
#include <iup.h>

static Ihandle* named[    173 ];

static void image_imgLine (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgLine", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgClip (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgClip", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgImage (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 2, 2, 2, 1, 3, 2, 2, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 1, 3, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 2, 2, 2, 1, 1, 2, 2, 1, 3, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 3, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 2, 1, 3, 1, 2, 1, 3, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 2, 2, 1, 3, 2, 1, 3, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 1, 3, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgImage", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", 
    "3", "153 153 153", NULL );
}

static void image_imgImageRGB (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgImageRGB", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "255 0 0", 
    "2", "0 255 0", 
    "3", "0 0 255", NULL );
}

static void image_imgBox (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgBox", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgRect (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgRect", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgSector (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgSector", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgChord (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgChord", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgArc (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgArc", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgText (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 0,
     0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgText", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "255 255 255", 
    "2", "0 0 0", NULL );
}

static void image_imgPoly (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgPoly", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgMark (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgMark", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgPixel (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
     0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  IupSetAtt( "imgPixel", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}


void cdtest_loadled (void)
{
  image_imgLine ();
  image_imgClip ();
  image_imgImage ();
  image_imgImageRGB ();
  image_imgBox ();
  image_imgRect ();
  image_imgSector ();
  image_imgChord ();
  image_imgArc ();
  image_imgText ();
  image_imgPoly ();
  image_imgMark ();
  image_imgPixel ();
  named[0] = IupSetAtt( "mnOpen", IupMenu(
    IupItem( "MF...", "cmdPlayMF" ),
    named[1] = IupSetAtt( "itPlayCGM", IupItem( "CGM...", "cmdPlayCGM" ), 
      "ACTIVE", "NO", NULL ),
    named[2] = IupSetAtt( "itPlayEMF", IupItem( "EMF...", "cmdPlayEMF" ), 
      "ACTIVE", "NO", NULL ),
    named[3] = IupSetAtt( "itPlayWMF", IupItem( "WMF...", "cmdPlayWMF" ), 
      "ACTIVE", "NO", NULL ),
  NULL), NULL );
  named[4] = IupSetAtt( "mnSave", IupMenu(
    IupItem( "MF...", "cmdMF" ),
    IupItem( "DEBUG...", "cmdDebug" ),
    named[5] = IupSetAtt( "itPDF", IupItem( "PDF...", "cmdPDF" ), 
      "ACTIVE", "NO", NULL ),
    named[6] = IupSetAtt( "itPS", IupItem( "PS...", "cmdPS" ), 
      "ACTIVE", "NO", NULL ),
    named[7] = IupSetAtt( "itEPS", IupItem( "EPS...", "cmdEPS" ), 
      "ACTIVE", "NO", NULL ),
    named[8] = IupSetAtt( "itSVG", IupItem( "SVG...", "cmdSVG" ), 
      "ACTIVE", "NO", NULL ),
    named[9] = IupSetAtt( "itCGMt", IupItem( "CGMt...", "cmdCGMt" ), 
      "ACTIVE", "NO", NULL ),
    named[10] = IupSetAtt( "itCGMb", IupItem( "CGMb...", "cmdCGMb" ), 
      "ACTIVE", "NO", NULL ),
    named[11] = IupSetAtt( "itDGN", IupItem( "DGN...", "cmdDGN" ), 
      "ACTIVE", "NO", NULL ),
    named[12] = IupSetAtt( "itDXF", IupItem( "DXF...", "cmdDXF" ), 
      "ACTIVE", "NO", NULL ),
    named[13] = IupSetAtt( "itEMF", IupItem( "EMF...", "cmdEMF" ), 
      "ACTIVE", "NO", NULL ),
    named[14] = IupSetAtt( "itWMF", IupItem( "WMF...", "cmdWMF" ), 
      "ACTIVE", "NO", NULL ),
  NULL), NULL );
  named[15] = IupSetAtt( "mnFile", IupMenu(
    IupSetAtt( NULL, IupSubmenu( "Open",
      named[0] /* mnOpen */
    ), 
      "KEY", "K_O", NULL ),
    IupSeparator(),
    IupSetAtt( NULL, IupSubmenu( "Save",
      named[4] /* mnSave */
    ), 
      "KEY", "K_S", NULL ),
    IupSeparator(),
    named[16] = IupSetAtt( "itPrint", IupItem( "Print...", "cmdPrint" ), 
      "KEY", "K_P", NULL ),
    IupSeparator(),
    IupSetAtt( NULL, IupItem( "Exit", "cmdFileExit" ), 
      "KEY", "K_x", NULL ),
  NULL), NULL );
  named[17] = IupSetAtt( "mnEdit", IupMenu(
    named[18] = IupSetAtt( "itEditUndo", IupItem( "Undo", "cmdEditUndo" ), NULL ),
    IupSeparator(),
    named[19] = IupSetAtt( "itClipBoard", IupItem( "Copy as EMF/WMF", "cmdClipBoard" ), 
      "ACTIVE", "NO", NULL ),
    named[20] = IupSetAtt( "itClipBoardBitmap", IupItem( "Copy as Bitmap", "cmdClipBoardBitmap" ), 
      "ACTIVE", "NO", NULL ),
    named[21] = IupSetAtt( "itClipBoardMetafile", IupItem( "Copy as CD Metafile", "cmdClipBoardMetafile" ), 
      "ACTIVE", "NO", NULL ),
    named[22] = IupSetAtt( "itClipBoardPaste", IupItem( "Paste", "cmdClipBoardPaste" ), 
      "ACTIVE", "NO", NULL ),
    IupSeparator(),
    IupItem( "Clear", "cmdEditClear" ),
    IupSeparator(),
    IupItem( "Options...", "cmdOptions" ),
  NULL), NULL );
  named[23] = IupSetAtt( "mnPrimitives", IupMenu(
    IupItem( "Pixel...", "cmdPixel" ),
    IupItem( "Mark...", "cmdMark" ),
    IupItem( "Line...", "cmdLine" ),
    IupItem( "Polygon...", "cmdPoly" ),
    IupItem( "Rect...", "cmdRect" ),
    IupItem( "Box...", "cmdBox" ),
    IupItem( "Arc...", "cmdArc" ),
    IupItem( "Sector...", "cmdSector" ),
    IupItem( "Chord...", "cmdChord" ),
    IupItem( "Text...", "cmdText" ),
    IupSeparator(),
    IupItem( "Server Image...", "cmdImage" ),
    IupItem( "RGB Image...", "cmdImageRGB" ),
  NULL), NULL );
  named[24] = IupSetAtt( "mnDraw", IupMenu(
    IupSetAtt( NULL, IupSubmenu( "Primitives",
      named[23] /* mnPrimitives */
    ), 
      "KEY", "K_P", NULL ),
    IupSeparator(),
    IupItem( "Clipping...", "cmdClip" ),
    IupItem( "Attributes...", "cmdAttributes" ),
    IupSeparator(),
    named[25] = IupSetAtt( "itWDCanvas", IupItem( "Show WD Canvas", "cmdWDCanvas" ), NULL ),
    named[26] = IupSetAtt( "itPICCanvas", IupItem( "Show Picture Canvas", "cmdPICCanvas" ), NULL ),
  NULL), 
    "ISMENU", "YES", NULL );
  named[27] = IupSetAtt( "mnHelp", IupMenu(
    IupItem( "About...", "cmdHelpAbout" ),
  NULL), NULL );
  named[28] = IupSetAtt( "mnMain", IupMenu(
    IupSetAtt( NULL, IupSubmenu( "File",
      named[15] /* mnFile */
    ), 
      "KEY", "K_mF", NULL ),
    IupSetAtt( NULL, IupSubmenu( "Edit",
      named[17] /* mnEdit */
    ), 
      "KEY", "K_mE", NULL ),
    IupSetAtt( NULL, IupSubmenu( "Draw",
      named[24] /* mnDraw */
    ), 
      "KEY", "K_mD", NULL ),
    IupSetAtt( NULL, IupSubmenu( "Help",
      named[27] /* mnHelp */
    ), 
      "KEY", "K_mH", NULL ),
  NULL), NULL );
  named[29] = IupSetAtt( "lbStatusLine", IupLabel( "Esta eh a barra de status do CDTest." ), 
    "EXPAND", "HORIZONTAL", NULL );
  named[30] = IupSetAtt( "btLine", IupButton( "", "cmdLine" ), 
    "IMAGE", "imgLine", 
    "TIP", "Line", NULL );
  named[31] = IupSetAtt( "btBox", IupButton( "", "cmdBox" ), 
    "IMAGE", "imgBox", 
    "TIP", "Box", NULL );
  named[32] = IupSetAtt( "btRect", IupButton( "", "cmdRect" ), 
    "IMAGE", "imgRect", 
    "TIP", "Rect", NULL );
  named[33] = IupSetAtt( "btArc", IupButton( "", "cmdArc" ), 
    "IMAGE", "imgArc", 
    "TIP", "Arc", NULL );
  named[34] = IupSetAtt( "btSector", IupButton( "", "cmdSector" ), 
    "IMAGE", "imgSector", 
    "TIP", "Sector", NULL );
  named[35] = IupSetAtt( "btChord", IupButton( "", "cmdChord" ), 
    "IMAGE", "imgChord", 
    "TIP", "Chord", NULL );
  named[36] = IupSetAtt( "btPixel", IupButton( "", "cmdPixel" ), 
    "IMAGE", "imgPixel", 
    "TIP", "Pixel", NULL );
  named[37] = IupSetAtt( "btMark", IupButton( "", "cmdMark" ), 
    "IMAGE", "imgMark", 
    "TIP", "Mark", NULL );
  named[38] = IupSetAtt( "btText", IupButton( "", "cmdText" ), 
    "IMAGE", "imgText", 
    "TIP", "Text", NULL );
  named[39] = IupSetAtt( "btPoly", IupButton( "", "cmdPoly" ), 
    "IMAGE", "imgPoly", 
    "TIP", "Polygon", NULL );
  named[40] = IupSetAtt( "btImageRGB", IupButton( "", "cmdImageRGB" ), 
    "IMAGE", "imgImageRGB", 
    "TIP", "RGB Image", NULL );
  named[41] = IupSetAtt( "btImage", IupButton( "", "cmdImage" ), 
    "IMAGE", "imgImage", 
    "TIP", "Server Image", NULL );
  named[42] = IupSetAtt( "btClip", IupButton( "", "cmdClip" ), 
    "IMAGE", "imgClip", 
    "TIP", "Clipping Area", NULL );
  named[43] = IupSetAtt( "btCurPrim", IupButton( "", "cmdShowDialog" ), 
    "IMAGE", "imgLine", 
    "TIP", "Show primitive dialog", NULL );
  named[44] = IupSetAtt( "lbMousePos", IupLabel( "(    ,    )" ), 
    "SIZE", "90", NULL );
  named[45] = IupSetAtt( "PrimBar", IupVbox(
    named[43] /* btCurPrim */,
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "20", NULL ),
    named[36] /* btPixel */,
    named[37] /* btMark */,
    named[30] /* btLine */,
    named[39] /* btPoly */,
    named[32] /* btRect */,
    named[31] /* btBox */,
    named[33] /* btArc */,
    named[34] /* btSector */,
    named[35] /* btChord */,
    named[38] /* btText */,
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    named[41] /* btImage */,
    named[40] /* btImageRGB */,
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    named[42] /* btClip */,
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "30", NULL ),
  NULL), 
    "GAP", "2", NULL );
  named[46] = IupSetAtt( "cnvColorBar", IupCanvas( "cmdColorBarRepaint" ), 
    "BUTTON_CB", "cmdColorBarButtonCB", 
    "RESIZE_CB", "cmdColorBarResizeCB", 
    "SIZE", "220x12", 
    "BORDER", "NO", 
    "EXPAND", "NO", NULL );
  named[47] = IupSetAtt( "cnvMain", IupCanvas( "cmdRepaint" ), 
    "MOTION_CB", "cmdMotionCB", 
    "BUTTON_CB", "cmdButtonCB", 
    "RESIZE_CB", "cmdResizeCB", NULL );
  named[48] = IupSetAtt( "DeskTop", IupVbox(
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    IupHbox(
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[45] /* PrimBar */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "2", NULL ),
      IupVbox(
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "2", NULL ),
        named[44] /* lbMousePos */,
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "5", NULL ),
        named[47] /* cnvMain */,
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "2", NULL ),
        named[46] /* cnvColorBar */,
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "5", NULL ),
        named[29] /* lbStatusLine */,
      NULL),
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
    NULL),
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "5", NULL ),
  NULL), NULL );
  named[49] = IupSetAtt( "dlgMain", IupDialog(
    named[48] /* DeskTop */
  ), 
    "TITLE", "CD Test 5.3", 
    "MENU", "mnMain", 
    "ICON", "CdTestIcon", 
    "K_cZ", "cmdEditUndo", 
    "GETFOCUS_CB", "cmdGetFocusCB", 
    "KILLFOCUS_CB", "cmdKillFocusCB", 
    "CLOSE_CB", "cmdFileExit", NULL );
  named[50] = IupSetAtt( "cnvWDCanvas", IupCanvas( "cmdWDRepaint" ), 
    "BORDER", "NO", NULL );
  named[51] = IupSetAtt( "dlgWDCanvas", IupDialog(
    named[50] /* cnvWDCanvas */
  ), 
    "TITLE", "WD Canvas", 
    "CLISE_CB", "cmdCloseWD", 
    "SIZE", "200x200", 
    "PARENTDIALOG", "dlgMain", 
    "GAP", "5x5", NULL );
  named[52] = IupSetAtt( "cnvPICCanvas", IupCanvas( "cmdPICRepaint" ), 
    "BORDER", "NO", NULL );
  named[53] = IupSetAtt( "dlgPICCanvas", IupDialog(
    named[52] /* cnvPICCanvas */
  ), 
    "TITLE", "PIC Canvas", 
    "CLISE_CB", "cmdClosePIC", 
    "SIZE", "200x200", 
    "PARENTDIALOG", "dlgMain", 
    "GAP", "5x5", NULL );
  named[54] = IupSetAtt( "btOptionsHide", IupButton( "Hide", "cmdOptionsHide" ), 
    "SIZE", "30", NULL );
  named[55] = IupSetAtt( "tgSimulate", IupToggle( "Simulate", "cmdSimulate" ), 
    "VALUE", "OFF", 
    "SIZE", "55", NULL );
  named[56] = IupSetAtt( "tgStretchPlay", IupToggle( "Stretch Play", "cmdStretchPlay" ), 
    "VALUE", "OFF", 
    "SIZE", "70", NULL );
  named[57] = IupSetAtt( "tgNoBuffering", IupToggle( "No buffering", "cmdNoBuffering" ), 
    "VALUE", "ON", NULL );
  named[58] = IupSetAtt( "tgImageBuffer", IupToggle( "CD_DBUFFER", "cmdImageBuffer" ), NULL );
  named[59] = IupSetAtt( "tgRGBBuffer", IupToggle( "CD_DBUFFERRGB", "cmdRGBBuffer" ), NULL );
  named[60] = IupSetAtt( "rdBuffering", IupRadio(
    IupVbox(
      named[57] /* tgNoBuffering */,
      named[58] /* tgImageBuffer */,
      named[59] /* tgRGBBuffer */,
    NULL)
  ), NULL );
  named[61] = IupSetAtt( "OptionsDesktop", IupVbox(
    IupSetAtt( NULL, IupVbox(
      IupSetAtt( NULL, IupFrame(
        named[60] /* rdBuffering */
      ), 
        "TITLE", "Buffering:", 
        "MARGIN", "5x5", 
        "SIZE", "80", NULL ),
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "10", NULL ),
      named[55] /* tgSimulate */,
      named[56] /* tgStretchPlay */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "10", NULL ),
      named[54] /* btOptionsHide */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "2", NULL ),
    NULL), 
      "GAP", "2", NULL ),
  NULL), NULL );
  named[62] = IupSetAtt( "dlgOptions", IupDialog(
    named[61] /* OptionsDesktop */
  ), 
    "TITLE", "Options", 
    "PARENTDIALOG", "dlgMain", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "MARGIN", "5x2", NULL );
  named[63] = IupSetAtt( "lstTextAlignment", IupList( "cmdTextAlignment" ), 
    "1", "CD_NORTH", 
    "2", "CD_SOUTH", 
    "3", "CD_EAST", 
    "4", "CD_WEST", 
    "5", "CD_NORTH_EAST", 
    "6", "CD_NORTH_WEST", 
    "7", "CD_SOUTH_EAST", 
    "8", "CD_SOUTH_WEST", 
    "9", "CD_CENTER", 
    "10", "CD_BASE_LEFT", 
    "11", "CD_BASE_CENTER", 
    "12", "CD_BASE_RIGHT", 
    "DROPDOWN", "YES", 
    "VALUE", "10", 
    "SIZE", "89", NULL );
  named[64] = IupSetAtt( "txtMarkSize", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "20x12", 
    "VALUE", "10", NULL );
  named[65] = IupSetAtt( "lstMarkType", IupList( "cmdMarkType" ), 
    "1", "CD_PLUS", 
    "2", "CD_STAR", 
    "3", "CD_CIRCLE", 
    "4", "CD_X", 
    "5", "CD_BOX", 
    "6", "CD_DIAMOND", 
    "7", "CD_HOLLOW_CIRCLE", 
    "8", "CD_HOLLOW_BOX", 
    "9", "CD_HOLLOW_DIAMOND", 
    "DROPDOWN", "YES", 
    "VALUE", "2", 
    "SIZE", "80", NULL );
  named[66] = IupSetAtt( "lstWriteMode", IupList( "cmdWriteMode" ), 
    "1", "CD_REPLACE", 
    "2", "CD_XOR", 
    "3", "CD_NOT_XOR", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[67] = IupSetAtt( "lstFontTypeFace", IupList( "cmdFontTypeFace" ), 
    "1", "CD_SYSTEM", 
    "2", "CD_COURIER", 
    "3", "CD_TIMES_ROMAN", 
    "4", "CD_HELVETICA", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[68] = IupSetAtt( "lstLineCap", IupList( "cmdLineCap" ), 
    "1", "CD_CAPFLAT", 
    "2", "CD_CAPSQUARE", 
    "3", "CD_CAPROUND", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[69] = IupSetAtt( "lstLineJoin", IupList( "cmdLineJoin" ), 
    "1", "CD_BEVEL", 
    "2", "CD_MITER", 
    "3", "CD_ROUND", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[70] = IupSetAtt( "lstFillMode", IupList( "cmdFillMode" ), 
    "1", "CD_EVENODD", 
    "2", "CD_WINDING", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[71] = IupSetAtt( "lstFontStyle", IupList( "cmdFontStyle" ), 
    "1", "CD_PLAIN", 
    "2", "CD_BOLD", 
    "3", "CD_ITALIC", 
    "4", "CD_BOLD_ITALIC", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[72] = IupSetAtt( "txtLineWidth", IupText( "cmdInteger" ), 
    "SIZE", "30", 
    "NC", "3", 
    "VALUE", "1", NULL );
  named[73] = IupSetAtt( "txtFontSize", IupText( "cmdInteger" ), 
    "SIZE", "30", 
    "NC", "3", 
    "VALUE", "12", NULL );
  named[74] = IupSetAtt( "txtTextOrientation", IupText( "cmdInteger" ), 
    "SIZE", "30", 
    "NC", "3", 
    "VALUE", "0", NULL );
  named[75] = IupSetAtt( "lstLineStyle", IupList( "cmdLineStyle" ), 
    "1", "CD_CONTINUOUS", 
    "2", "CD_DASHED", 
    "3", "CD_DOTTED", 
    "4", "CD_DASH_DOT", 
    "5", "CD_DASH_DOT_DOT", 
    "6", "CD_CUSTOM", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[76] = IupSetAtt( "tgSolid", IupToggle( "CD_SOLID", "cmdSolid" ), 
    "VALUE", "ON", NULL );
  named[77] = IupSetAtt( "tgHatch", IupToggle( "CD_HATCH", "cmdHatch" ), NULL );
  named[78] = IupSetAtt( "tgStipple", IupToggle( "CD_STIPPLE", "cmdStipple" ), NULL );
  named[79] = IupSetAtt( "tgPattern", IupToggle( "CD_PATTERN", "cmdPattern" ), NULL );
  named[80] = IupSetAtt( "lstOpacity", IupList( "cmdOpacity" ), 
    "1", "CD_OPAQUE", 
    "2", "CD_TRANSPARENT", 
    "VALUE", "2", 
    "DROPDOWN", "YES", 
    "SIZE", "80", 
    "ACTIVE", "YES", NULL );
  named[81] = IupSetAtt( "lstHatchStyle", IupList( "cmdHatchStyle" ), 
    "1", "CD_HORIZONTAL", 
    "2", "CD_VERTICAL", 
    "3", "CD_FDIAGONAL", 
    "4", "CD_BDIAGONAL", 
    "5", "CD_CROSS", 
    "6", "CD_DIAGCROSS", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", 
    "ACTIVE", "YES", NULL );
  named[82] = IupSetAtt( "btAttributesHide", IupButton( "Hide", "cmdAttributesHide" ), 
    "SIZE", "30", NULL );
  named[83] = IupSetAtt( "rdInteriorStyle", IupRadio(
    IupVbox(
      named[76] /* tgSolid */,
      named[77] /* tgHatch */,
      named[78] /* tgStipple */,
      named[79] /* tgPattern */,
    NULL)
  ), NULL );
  named[84] = IupSetAtt( "AttributesDesktop", IupVbox(
    IupHbox(
      IupSetAtt( NULL, IupVbox(
        IupLabel( "Write Mode:" ),
        named[66] /* lstWriteMode */,
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "4", NULL ),
        IupSetAtt( NULL, IupFrame(
          IupVbox(
            IupLabel( "Back Opacity:" ),
            named[80] /* lstOpacity */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Fill Mode:" ),
            named[70] /* lstFillMode */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupSetAtt( NULL, IupFrame(
              named[83] /* rdInteriorStyle */
            ), 
              "TITLE", "Interior Style:", 
              "MARGIN", "5x5", 
              "SIZE", "80", NULL ),
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Hatch Style:" ),
            named[81] /* lstHatchStyle */,
          NULL)
        ), 
          "TITLE", "Fill Attributes", 
          "MARGIN", "5x5", NULL ),
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "10", NULL ),
        IupSetAtt( NULL, IupFrame(
          IupVbox(
            IupLabel( "Mark Type:" ),
            named[65] /* lstMarkType */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Mark Size:" ),
            named[64] /* txtMarkSize */,
          NULL)
        ), 
          "TITLE", "Mark Attributes", 
          "MARGIN", "5x5", NULL ),
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "10", NULL ),
        named[82] /* btAttributesHide */,
      NULL), 
        "GAP", "2", NULL ),
      IupSetAtt( NULL, IupVbox(
        IupSetAtt( NULL, IupFrame(
          IupVbox(
            IupLabel( "Font Typeface:" ),
            named[67] /* lstFontTypeFace */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Font Style:" ),
            named[71] /* lstFontStyle */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Font Size:" ),
            named[73] /* txtFontSize */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupSetAtt( NULL, IupLabel( "Text Alignment:" ), 
              "SIZE", "x9", NULL ),
            named[63] /* lstTextAlignment */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupSetAtt( NULL, IupLabel( "Text Orientation:" ), 
              "SIZE", "x9", NULL ),
            named[74] /* txtTextOrientation */,
          NULL)
        ), 
          "TITLE", "Text Attributes", 
          "MARGIN", "5x5", NULL ),
        IupSetAtt( NULL, IupFill(), 
          "SIZE", "10", NULL ),
        IupSetAtt( NULL, IupFrame(
          IupVbox(
            IupLabel( "Line Style:" ),
            named[75] /* lstLineStyle */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Line Width:" ),
            named[72] /* txtLineWidth */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Line Cap:" ),
            named[68] /* lstLineCap */,
            IupSetAtt( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Line Join:" ),
            named[69] /* lstLineJoin */,
          NULL)
        ), 
          "TITLE", "Line Attributes", 
          "MARGIN", "5x5", NULL ),
      NULL), 
        "GAP", "2", NULL ),
    NULL),
  NULL), NULL );
  named[85] = IupSetAtt( "dlgAttributes", IupDialog(
    named[84] /* AttributesDesktop */
  ), 
    "TITLE", "Attributes", 
    "PARENTDIALOG", "dlgMain", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdAttributesHide", 
    "MARGIN", "5x2", NULL );
  named[86] = IupSetAtt( "txtLBX1", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[87] = IupSetAtt( "txtLBX2", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[88] = IupSetAtt( "txtLBY1", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[89] = IupSetAtt( "txtLBY2", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[90] = IupSetAtt( "btLBDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[91] = IupSetAtt( "btLBHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[92] = IupSetAtt( "LBData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "X1:" ), 
        "SIZE", "15x9", NULL ),
      named[86] /* txtLBX1 */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y1:" ), 
        "SIZE", "15x9", NULL ),
      named[88] /* txtLBY1 */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "X2:" ), 
        "SIZE", "15x9", NULL ),
      named[87] /* txtLBX2 */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y2:" ), 
        "SIZE", "15x9", NULL ),
      named[89] /* txtLBY2 */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[93] = IupSetAtt( "LBDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[92] /* LBData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[90] /* btLBDraw */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[91] /* btLBHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[94] = IupSetAtt( "dlgLB", IupDialog(
    named[93] /* LBDeskTop */
  ), 
    "TITLE", "Line Parameters", 
    "PARENTDIALOG", "dlgMain", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[95] = IupSetAtt( "txtASXC", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[96] = IupSetAtt( "txtASYC", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[97] = IupSetAtt( "txtASW", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[98] = IupSetAtt( "txtASH", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[99] = IupSetAtt( "txtASAngle1", IupText( "cmdReal" ), 
    "NC", "10", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[100] = IupSetAtt( "txtASAngle2", IupText( "cmdReal" ), 
    "NC", "10", 
    "SIZE", "30x12", 
    "VALUE", "360", NULL );
  named[101] = IupSetAtt( "btASDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[102] = IupSetAtt( "btASHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[103] = IupSetAtt( "ASData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "Xc:" ), 
        "SIZE", "30x9", NULL ),
      named[95] /* txtASXC */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Yc:" ), 
        "SIZE", "30x9", NULL ),
      named[96] /* txtASYC */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "W:" ), 
        "SIZE", "30x9", NULL ),
      named[97] /* txtASW */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "H:" ), 
        "SIZE", "30x9", NULL ),
      named[98] /* txtASH */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "Angle1:" ), 
        "SIZE", "30x9", NULL ),
      named[99] /* txtASAngle1 */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Angle2:" ), 
        "SIZE", "30x9", NULL ),
      named[100] /* txtASAngle2 */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[104] = IupSetAtt( "ASDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[103] /* ASData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[101] /* btASDraw */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[102] /* btASHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[105] = IupSetAtt( "dlgAS", IupDialog(
    named[104] /* ASDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Arc Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[106] = IupSetAtt( "txtPixelX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[107] = IupSetAtt( "txtPixelY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[108] = IupSetAtt( "btPixelDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[109] = IupSetAtt( "btPixelHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[110] = IupSetAtt( "PixelData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "X:" ), 
        "SIZE", "10x9", NULL ),
      named[106] /* txtPixelX */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y:" ), 
        "SIZE", "10x9", NULL ),
      named[107] /* txtPixelY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[111] = IupSetAtt( "PixelDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[110] /* PixelData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[108] /* btPixelDraw */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[109] /* btPixelHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[112] = IupSetAtt( "dlgPixel", IupDialog(
    named[111] /* PixelDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Pixel Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[113] = IupSetAtt( "txtMarkX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[114] = IupSetAtt( "txtMarkY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[115] = IupSetAtt( "btMarkDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[116] = IupSetAtt( "btMarkHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[117] = IupSetAtt( "MarkData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupFill(),
      IupSetAtt( NULL, IupLabel( "X:" ), 
        "SIZE", "10x9", NULL ),
      named[113] /* txtMarkX */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y:" ), 
        "SIZE", "10x9", NULL ),
      named[114] /* txtMarkY */,
      IupFill(),
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[118] = IupSetAtt( "MarkDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[117] /* MarkData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[115] /* btMarkDraw */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[116] /* btMarkHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[119] = IupSetAtt( "dlgMark", IupDialog(
    named[118] /* MarkDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Mark Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[120] = IupSetAtt( "txtTextX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[121] = IupSetAtt( "txtTextY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[122] = IupSetAtt( "txtTextS", IupText( "cmdString" ), 
    "NC", "100", 
    "SIZE", "89x12", 
    "VALUE", "Text", NULL );
  named[123] = IupSetAtt( "btTextDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[124] = IupSetAtt( "btTextHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[125] = IupSetAtt( "TextData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "X:" ), 
        "SIZE", "10x9", NULL ),
      named[120] /* txtTextX */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y:" ), 
        "SIZE", "10x9", NULL ),
      named[121] /* txtTextY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupHbox(
      IupVbox(
        IupSetAtt( NULL, IupLabel( "Text:" ), 
          "SIZE", "25x9", NULL ),
        named[122] /* txtTextS */,
      NULL),
    NULL),
  NULL), NULL );
  named[126] = IupSetAtt( "TextDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[125] /* TextData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[123] /* btTextDraw */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[124] /* btTextHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[127] = IupSetAtt( "dlgText", IupDialog(
    named[126] /* TextDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Text Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[128] = IupSetAtt( "tgOpenLines", IupToggle( "CD_OPEN_LINES", "cmdOpenLines" ), 
    "VALUE", "ON", NULL );
  named[129] = IupSetAtt( "tgClosedLines", IupToggle( "CD_CLOSED_LINES", "cmdClosedLines" ), NULL );
  named[130] = IupSetAtt( "tgFilled", IupToggle( "CD_FILL", "cmdFill" ), NULL );
  named[131] = IupSetAtt( "tgClip", IupToggle( "CD_CLIP", "cmdPolyClip" ), NULL );
  named[132] = IupSetAtt( "tgBezier", IupToggle( "CD_BEZIER", "cmdPolyBezier" ), NULL );
  named[133] = IupSetAtt( "btPolyHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[134] = IupSetAtt( "rdMode", IupRadio(
    IupVbox(
      named[128] /* tgOpenLines */,
      named[129] /* tgClosedLines */,
      named[130] /* tgFilled */,
      named[131] /* tgClip */,
      named[132] /* tgBezier */,
    NULL)
  ), NULL );
  named[135] = IupSetAtt( "PolyDesktop", IupVbox(
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    IupHbox(
      IupFill(),
      IupSetAtt( NULL, IupFrame(
        IupHbox(
          IupSetAtt( NULL, IupFill(), 
            "SIZE", "5", NULL ),
          named[134] /* rdMode */,
        NULL)
      ), 
        "TITLE", "Polygon Mode:", NULL ),
      IupFill(),
    NULL),
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "10", NULL ),
    IupHbox(
      IupFill(),
      named[133] /* btPolyHide */,
      IupFill(),
    NULL),
    IupSetAtt( NULL, IupFill(), 
      "SIZE", "5", NULL ),
  NULL), NULL );
  named[136] = IupSetAtt( "dlgPoly", IupDialog(
    named[135] /* PolyDesktop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Polygon Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", NULL );
  named[137] = IupSetAtt( "txtClipXmin", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[138] = IupSetAtt( "txtClipXmax", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[139] = IupSetAtt( "txtClipYmin", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[140] = IupSetAtt( "txtClipYmax", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[141] = IupSetAtt( "btClipOff", IupButton( "Off", "cmdClipOff" ), 
    "SIZE", "30", NULL );
  named[142] = IupSetAtt( "btClipArea", IupButton( "Area", "cmdClipArea" ), 
    "SIZE", "30", NULL );
  named[143] = IupSetAtt( "btClipPoly", IupButton( "Polygon", "cmdClipPoly" ), 
    "SIZE", "50", NULL );
  named[144] = IupSetAtt( "btClipHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[145] = IupSetAtt( "ClipData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "Xmin:" ), 
        "SIZE", "25x9", NULL ),
      named[137] /* txtClipXmin */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Ymin:" ), 
        "SIZE", "25x9", NULL ),
      named[139] /* txtClipYmin */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "Xmax:" ), 
        "SIZE", "25x9", NULL ),
      named[138] /* txtClipXmax */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Ymax:" ), 
        "SIZE", "25x9", NULL ),
      named[140] /* txtClipYmax */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[146] = IupSetAtt( "ClipDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[145] /* ClipData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[141] /* btClipOff */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[142] /* btClipArea */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[143] /* btClipPoly */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[144] /* btClipHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[147] = IupSetAtt( "dlgClip", IupDialog(
    named[146] /* ClipDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Clipping", 
    "MAXBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[148] = IupSetAtt( "txtImageX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[149] = IupSetAtt( "txtImageY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[150] = IupSetAtt( "txtImageW", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[151] = IupSetAtt( "txtImageH", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[152] = IupSetAtt( "btImagePut", IupButton( "Put", "cmdImagePut" ), 
    "SIZE", "30", NULL );
  named[153] = IupSetAtt( "btImageGet", IupButton( "Get", "cmdImageGet" ), 
    "SIZE", "30", NULL );
  named[154] = IupSetAtt( "btImageHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[155] = IupSetAtt( "ImageData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "X:" ), 
        "SIZE", "30x9", NULL ),
      named[148] /* txtImageX */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y:" ), 
        "SIZE", "30x9", NULL ),
      named[149] /* txtImageY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "Width:" ), 
        "SIZE", "30x9", NULL ),
      named[150] /* txtImageW */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Height:" ), 
        "SIZE", "30x9", NULL ),
      named[151] /* txtImageH */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[156] = IupSetAtt( "ImageDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[155] /* ImageData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[153] /* btImageGet */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[152] /* btImagePut */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[154] /* btImageHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[157] = IupSetAtt( "dlgImage", IupDialog(
    named[156] /* ImageDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Server Image", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[158] = IupSetAtt( "txtImageRGBX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[159] = IupSetAtt( "txtImageRGBY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[160] = IupSetAtt( "txtImageRGBW", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[161] = IupSetAtt( "txtImageRGBH", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[162] = IupSetAtt( "btImageRGBPut", IupButton( "Put", "cmdImageRGBPut" ), 
    "SIZE", "30", NULL );
  named[163] = IupSetAtt( "btImageRGBGet", IupButton( "Get", "cmdImageRGBGet" ), 
    "SIZE", "30", NULL );
  named[164] = IupSetAtt( "btImageRGBHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[165] = IupSetAtt( "ImageRGBData", IupVbox(
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "X:" ), 
        "SIZE", "30x9", NULL ),
      named[158] /* txtImageRGBX */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Y:" ), 
        "SIZE", "30x9", NULL ),
      named[159] /* txtImageRGBY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupSetAtt( NULL, IupHbox(
      IupSetAtt( NULL, IupLabel( "Width:" ), 
        "SIZE", "30x9", NULL ),
      named[160] /* txtImageRGBW */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupSetAtt( NULL, IupLabel( "Height:" ), 
        "SIZE", "30x9", NULL ),
      named[161] /* txtImageRGBH */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[166] = IupSetAtt( "ImageRGBDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[165] /* ImageRGBData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[163] /* btImageRGBGet */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[162] /* btImageRGBPut */,
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[164] /* btImageRGBHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[167] = IupSetAtt( "dlgImageRGB", IupDialog(
    named[166] /* ImageRGBDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "RGB Image", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[168] = IupSetAtt( "btCDTest", IupButton( "Close", "cmdCloseAbout" ), NULL );
  named[169] = IupSetAtt( "AboutDeskTop", IupHbox(
    IupFill(),
    IupSetAtt( NULL, IupVbox(
      IupLabel( "CD Test 5.3" ),
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupLabel( "Antonio Scuri" ),
      IupLabel( "Diego Nehab" ),
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupLabel( "Tecgraf/PUC-Rio" ),
      IupSetAtt( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupLabel( "CD Library Version" ),
      named[170] = IupSetAtt( "lblVersion", IupLabel( "" ), NULL ),
      named[168] /* btCDTest */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupFill(),
  NULL), 
    "MARGIN", "5x5", 
    "GAP", "2", NULL );
  named[171] = IupSetAtt( "dlgHelpAbout", IupDialog(
    named[169] /* AboutDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "About", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", NULL );
}
