build={
 modules={

      ["global"]            = "lua_src/global.lua",

      ["wetgenes"]            = "lua_src/wetgenes/init.lua",
      ["wetgenes.csv"]        = "lua_src/wetgenes/csv.lua",
      ["wetgenes.diff"]       = "lua_src/wetgenes/diff.lua",
      ["wetgenes.getsql"]     = "lua_src/wetgenes/getsql.lua",
      ["wetgenes.gists"]      = "lua_src/wetgenes/gists.lua",
      ["wetgenes.html"]       = "lua_src/wetgenes/html.lua",
      ["wetgenes.json_diff"]  = "lua_src/wetgenes/json_diff.lua",
      ["wetgenes.msgp"]       = "lua_src/wetgenes/msgp.lua",
      ["wetgenes.logs"]       = "lua_src/wetgenes/logs.lua",
      ["wetgenes.package"]    = "lua_src/wetgenes/package.lua",
      ["wetgenes.path"]       = "lua_src/wetgenes/path.lua",
      ["wetgenes.plate"]      = "lua_src/wetgenes/plate.lua",
      ["wetgenes.pp"]         = "lua_src/wetgenes/pp.lua",
      ["wetgenes.ques"]       = "lua_src/wetgenes/ques.lua",
      ["wetgenes.sandbox"]    = "lua_src/wetgenes/sandbox.lua",
      ["wetgenes.simpxml"]    = "lua_src/wetgenes/simpxml.lua",
      ["wetgenes.spew"]       = "lua_src/wetgenes/spew.lua",
      ["wetgenes.string"]     = "lua_src/wetgenes/string.lua",
      ["wetgenes.syncs"]      = "lua_src/wetgenes/syncs.lua",
      ["wetgenes.tardis"]     = "lua_src/wetgenes/tardis.lua",
      ["wetgenes.tongues"]    = "lua_src/wetgenes/tongues.lua",
      ["wetgenes.tsv"]        = "lua_src/wetgenes/tsv.lua",
      ["wetgenes.zipsloader"] = "lua_src/wetgenes/zipsloader.lua",
      ["wetgenes.zips"]       = "lua_src/wetgenes/zips.lua",

      ["wetgenes.txt"]             = "lua_src/wetgenes/txt/init.lua",
      ["wetgenes.txt.diff"]        = "lua_src/wetgenes/txt/diff.lua",
      ["wetgenes.txt.edit"]        = "lua_src/wetgenes/txt/edit.lua",
      ["wetgenes.txt.ipa_symbols"] = "lua_src/wetgenes/txt/ipa_symbols.lua",
      ["wetgenes.txt.lex_glsl"]    = "lua_src/wetgenes/txt/lex_glsl.lua",
      ["wetgenes.txt.lex_js"]      = "lua_src/wetgenes/txt/lex_js.lua",
      ["wetgenes.txt.lex_lua"]     = "lua_src/wetgenes/txt/lex_lua.lua",
      ["wetgenes.txt.lex_txt"]     = "lua_src/wetgenes/txt/lex_txt.lua",
      ["wetgenes.txt.undo"]        = "lua_src/wetgenes/txt/undo.lua",
      ["wetgenes.txt.utf"]         = "lua_src/wetgenes/txt/utf.lua",
      ["wetgenes.txt.words"]       = "lua_src/wetgenes/txt/words.lua",

      ["wetgenes.bake"]            = "lua_src/wetgenes/bake/init.lua",
      ["wetgenes.bake.gamecake"]   = "lua_src/wetgenes/bake/gamecake.lua",
      ["wetgenes.bake.grd"]        = "lua_src/wetgenes/bake/grd.lua",
      ["wetgenes.bake.js"]         = "lua_src/wetgenes/bake/js.lua",
      ["wetgenes.bake.ngx"]        = "lua_src/wetgenes/bake/ngx.lua",
      ["wetgenes.bake.pathfix"]    = "lua_src/wetgenes/bake/pathfix.lua",
      ["wetgenes.bake.swf"]        = "lua_src/wetgenes/bake/swf.lua",

      ["wetgenes.win"]             = "lua_src/wetgenes/win.lua",
      ["wetgenes.win.android"]     = "lua_src/wetgenes/win/android.lua",
      ["wetgenes.win.emcc"]        = "lua_src/wetgenes/win/emcc.lua",
      ["wetgenes.win.linux"]       = "lua_src/wetgenes/win/linux.lua",
      ["wetgenes.win.nacl"]        = "lua_src/wetgenes/win/nacl.lua",
      ["wetgenes.win.osx"]         = "lua_src/wetgenes/win/osx.lua",
      ["wetgenes.win.posix"]       = "lua_src/wetgenes/win/posix.lua",
      ["wetgenes.win.raspi"]       = "lua_src/wetgenes/win/raspi.lua",
      ["wetgenes.win.sdl"]         = "lua_src/wetgenes/win/sdl.lua",
      ["wetgenes.win.steam"]       = "lua_src/wetgenes/win/steam.lua",
      ["wetgenes.win.windows"]     = "lua_src/wetgenes/win/windows.lua",

      ["wetgenes.gamecake.buffers"]      = "lua_src/wetgenes/gamecake/buffers.lua",
      ["wetgenes.gamecake.cake"]         = "lua_src/wetgenes/gamecake/cake.lua",
      ["wetgenes.gamecake.canvas"]       = "lua_src/wetgenes/gamecake/canvas.lua",
      ["wetgenes.gamecake.flat"]         = "lua_src/wetgenes/gamecake/flat.lua",
      ["wetgenes.gamecake.font"]         = "lua_src/wetgenes/gamecake/font.lua",
      ["wetgenes.gamecake.fonts"]        = "lua_src/wetgenes/gamecake/fonts.lua",
      ["wetgenes.gamecake.framebuffers"] = "lua_src/wetgenes/gamecake/framebuffers.lua",
      ["wetgenes.gamecake.gles"]         = "lua_src/wetgenes/gamecake/gles.lua",
      ["wetgenes.gamecake.images"]       = "lua_src/wetgenes/gamecake/images.lua",
      ["wetgenes.gamecake.layouts"]      = "lua_src/wetgenes/gamecake/layouts.lua",
      ["wetgenes.gamecake.oven"]         = "lua_src/wetgenes/gamecake/oven.lua",
      ["wetgenes.gamecake.sheets"]       = "lua_src/wetgenes/gamecake/sheets.lua",
      ["wetgenes.gamecake.sounds"]       = "lua_src/wetgenes/gamecake/sounds.lua",
      ["wetgenes.gamecake.stash"]        = "lua_src/wetgenes/gamecake/stash.lua",
      ["wetgenes.gamecake.textures"]     = "lua_src/wetgenes/gamecake/textures.lua",
      ["wetgenes.gamecake.toaster"]      = "lua_src/wetgenes/gamecake/toaster.lua",
      ["wetgenes.gamecake.upnet"]        = "lua_src/wetgenes/gamecake/upnet.lua",
      ["wetgenes.gamecake.ups"]          = "lua_src/wetgenes/gamecake/ups.lua",
      ["wetgenes.gamecake.views"]        = "lua_src/wetgenes/gamecake/views.lua",

      ["wetgenes.gamecake.mods.console"]          = "lua_src/wetgenes/gamecake/mods/console.lua",
      ["wetgenes.gamecake.mods.console.buffedit"] = "lua_src/wetgenes/gamecake/mods/console/buffedit.lua",
      ["wetgenes.gamecake.mods.escmenu"]          = "lua_src/wetgenes/gamecake/mods/escmenu.lua",
      ["wetgenes.gamecake.mods.keys"]             = "lua_src/wetgenes/gamecake/mods/keys.lua",
      ["wetgenes.gamecake.mods.layout"]           = "lua_src/wetgenes/gamecake/mods/layout.lua",
      ["wetgenes.gamecake.mods.mouse"]            = "lua_src/wetgenes/gamecake/mods/mouse.lua",
      ["wetgenes.gamecake.mods.snaps"]            = "lua_src/wetgenes/gamecake/mods/snaps.lua",

      ["wetgenes.gamecake.fun.autocell"]         = "lua_src/wetgenes/gamecake/fun/autocell.lua",
      ["wetgenes.gamecake.fun.bitdown_font_4x8"] = "lua_src/wetgenes/gamecake/fun/bitdown_font_4x8.lua",
      ["wetgenes.gamecake.fun.bitdown_font"]     = "lua_src/wetgenes/gamecake/fun/bitdown_font.lua",
      ["wetgenes.gamecake.fun.bitdown"]          = "lua_src/wetgenes/gamecake/fun/bitdown.lua",
      ["wetgenes.gamecake.fun.bitsynth"]         = "lua_src/wetgenes/gamecake/fun/bitsynth.lua",
      ["wetgenes.gamecake.fun.bitsynth_tracker"] = "lua_src/wetgenes/gamecake/fun/bitsynth_tracker.lua",
      ["wetgenes.gamecake.fun.canvas"]           = "lua_src/wetgenes/gamecake/fun/canvas.lua",
      ["wetgenes.gamecake.fun.chatdown"]         = "lua_src/wetgenes/gamecake/fun/chatdown.lua",
      ["wetgenes.gamecake.fun.colors"]           = "lua_src/wetgenes/gamecake/fun/colors.lua",
      ["wetgenes.gamecake.fun.copper"]           = "lua_src/wetgenes/gamecake/fun/copper.lua",
      ["wetgenes.gamecake.fun.entities"]         = "lua_src/wetgenes/gamecake/fun/entities.lua",
      ["wetgenes.gamecake.fun.funfont64"]        = "lua_src/wetgenes/gamecake/fun/funfont64.lua",
      ["wetgenes.gamecake.fun.main"]             = "lua_src/wetgenes/gamecake/fun/main.lua",
      ["wetgenes.gamecake.fun.overmap"]          = "lua_src/wetgenes/gamecake/fun/overmap.lua",
      ["wetgenes.gamecake.fun.screen"]           = "lua_src/wetgenes/gamecake/fun/screen.lua",
      ["wetgenes.gamecake.fun.sfx"]              = "lua_src/wetgenes/gamecake/fun/sfx.lua",
      ["wetgenes.gamecake.fun.sprites"]          = "lua_src/wetgenes/gamecake/fun/sprites.lua",
      ["wetgenes.gamecake.fun.system"]           = "lua_src/wetgenes/gamecake/fun/system.lua",
      ["wetgenes.gamecake.fun.texgenes"]         = "lua_src/wetgenes/gamecake/fun/texgenes.lua",
      ["wetgenes.gamecake.fun.tilemap"]          = "lua_src/wetgenes/gamecake/fun/tilemap.lua",
      ["wetgenes.gamecake.fun.tilemap_text"]     = "lua_src/wetgenes/gamecake/fun/tilemap_text.lua",
      ["wetgenes.gamecake.fun.tiles"]            = "lua_src/wetgenes/gamecake/fun/tiles.lua",
      ["wetgenes.gamecake.fun.yarn.cells"]       = "lua_src/wetgenes/gamecake/fun/yarn/cells.lua",
      ["wetgenes.gamecake.fun.yarn.items"]       = "lua_src/wetgenes/gamecake/fun/yarn/items.lua",
      ["wetgenes.gamecake.fun.yarn.pages"]       = "lua_src/wetgenes/gamecake/fun/yarn/pages.lua",
      ["wetgenes.gamecake.fun.yarn.prefabs"]     = "lua_src/wetgenes/gamecake/fun/yarn/prefabs.lua",
      ["wetgenes.gamecake.fun.yarn.rules"]       = "lua_src/wetgenes/gamecake/fun/yarn/rules.lua",

      ["wetgenes.gamecake.widgets"]              = "lua_src/wetgenes/gamecake/widgets/init.lua",
      ["wetgenes.gamecake.widgets.button"]       = "lua_src/wetgenes/gamecake/widgets/button.lua",
      ["wetgenes.gamecake.widgets.center"]       = "lua_src/wetgenes/gamecake/widgets/center.lua",
      ["wetgenes.gamecake.widgets.checkbox"]     = "lua_src/wetgenes/gamecake/widgets/checkbox.lua",
      ["wetgenes.gamecake.widgets.data"]         = "lua_src/wetgenes/gamecake/widgets/data.lua",
      ["wetgenes.gamecake.widgets.datas"]        = "lua_src/wetgenes/gamecake/widgets/datas.lua",
      ["wetgenes.gamecake.widgets.defs"]         = "lua_src/wetgenes/gamecake/widgets/defs.lua",
      ["wetgenes.gamecake.widgets.dialogs"]      = "lua_src/wetgenes/gamecake/widgets/dialogs.lua",
      ["wetgenes.gamecake.widgets.drag"]         = "lua_src/wetgenes/gamecake/widgets/drag.lua",
      ["wetgenes.gamecake.widgets.file"]         = "lua_src/wetgenes/gamecake/widgets/file.lua",
      ["wetgenes.gamecake.widgets.fill"]         = "lua_src/wetgenes/gamecake/widgets/fill.lua",
      ["wetgenes.gamecake.widgets.line"]         = "lua_src/wetgenes/gamecake/widgets/line.lua",
      ["wetgenes.gamecake.widgets.master"]       = "lua_src/wetgenes/gamecake/widgets/master.lua",
      ["wetgenes.gamecake.widgets.menubar"]      = "lua_src/wetgenes/gamecake/widgets/menubar.lua",
      ["wetgenes.gamecake.widgets.menudrop"]     = "lua_src/wetgenes/gamecake/widgets/menudrop.lua",
      ["wetgenes.gamecake.widgets.menuitem"]     = "lua_src/wetgenes/gamecake/widgets/menuitem.lua",
      ["wetgenes.gamecake.widgets.menu"]         = "lua_src/wetgenes/gamecake/widgets/menu.lua",
      ["wetgenes.gamecake.widgets.menutoggle"]   = "lua_src/wetgenes/gamecake/widgets/menutoggle.lua",
      ["wetgenes.gamecake.widgets.meta"]         = "lua_src/wetgenes/gamecake/widgets/meta.lua",
      ["wetgenes.gamecake.widgets.mounts"]       = "lua_src/wetgenes/gamecake/widgets/mounts.lua",
      ["wetgenes.gamecake.widgets.pages"]        = "lua_src/wetgenes/gamecake/widgets/pages.lua",
      ["wetgenes.gamecake.widgets.pan"]          = "lua_src/wetgenes/gamecake/widgets/pan.lua",
      ["wetgenes.gamecake.widgets.paragraph"]    = "lua_src/wetgenes/gamecake/widgets/paragraph.lua",
      ["wetgenes.gamecake.widgets.quad"]         = "lua_src/wetgenes/gamecake/widgets/quad.lua",
      ["wetgenes.gamecake.widgets.screen"]       = "lua_src/wetgenes/gamecake/widgets/screen.lua",
      ["wetgenes.gamecake.widgets.scroll"]       = "lua_src/wetgenes/gamecake/widgets/scroll.lua",
      ["wetgenes.gamecake.widgets.skin"]         = "lua_src/wetgenes/gamecake/widgets/skin.lua",
      ["wetgenes.gamecake.widgets.slide"]        = "lua_src/wetgenes/gamecake/widgets/slide.lua",
      ["wetgenes.gamecake.widgets.split_drag"]   = "lua_src/wetgenes/gamecake/widgets/split_drag.lua",
      ["wetgenes.gamecake.widgets.split"]        = "lua_src/wetgenes/gamecake/widgets/split.lua",
      ["wetgenes.gamecake.widgets.tabpages"]     = "lua_src/wetgenes/gamecake/widgets/tabpages.lua",
      ["wetgenes.gamecake.widgets.tabs"]         = "lua_src/wetgenes/gamecake/widgets/tabs.lua",
      ["wetgenes.gamecake.widgets.textedit"]     = "lua_src/wetgenes/gamecake/widgets/textedit.lua",
      ["wetgenes.gamecake.widgets.texteditor"]   = "lua_src/wetgenes/gamecake/widgets/texteditor.lua",
      ["wetgenes.gamecake.widgets.text"]         = "lua_src/wetgenes/gamecake/widgets/text.lua",
      ["wetgenes.gamecake.widgets.textmap"]      = "lua_src/wetgenes/gamecake/widgets/textmap.lua",
      ["wetgenes.gamecake.widgets.three"]        = "lua_src/wetgenes/gamecake/widgets/three.lua",
      ["wetgenes.gamecake.widgets.tiles"]        = "lua_src/wetgenes/gamecake/widgets/tiles.lua",
      ["wetgenes.gamecake.widgets.treefile"]     = "lua_src/wetgenes/gamecake/widgets/treefile.lua",
      ["wetgenes.gamecake.widgets.treegist"]     = "lua_src/wetgenes/gamecake/widgets/treegist.lua",
      ["wetgenes.gamecake.widgets.tree"]         = "lua_src/wetgenes/gamecake/widgets/tree.lua",
      ["wetgenes.gamecake.widgets.window"]       = "lua_src/wetgenes/gamecake/widgets/window.lua",
      ["wetgenes.gamecake.widgets.windows"]      = "lua_src/wetgenes/gamecake/widgets/windows.lua",

      ["cmd"]        = "lua_src/cmd/init.lua",
      ["cmd.args"]   = "lua_src/cmd/args.lua",
      ["cmd.dump"]   = "lua_src/cmd/dump.lua",
      ["cmd.grd"]    = "lua_src/cmd/grd.lua",
      ["cmd.help"]   = "lua_src/cmd/help.lua",
      ["cmd.http"]   = "lua_src/cmd/http.lua",
      ["cmd.midi"]   = "lua_src/cmd/midi.lua",
      ["cmd.sdl"]    = "lua_src/cmd/sdl.lua",
      ["cmd.args"]   = "lua_src/cmd/args.lua",
      ["cmd.avatar"] = "lua_src/cmd/avatar.lua",
      ["cmd.swed"]   = "lua_src/cmd/swed.lua",

 },
 platform={
  windows={
  },
 },
 type="builtin",
}
external_dependencies = {
}
dependencies={
 "lua >= 5.1 <= 5.2",
 "luautf8",
 "luafilesystem",
 "luaposix",
 "luazip",
 "lua-zlib",
 "luasocket",
 "luasec",
 "lsqlite3",
-- "luapgsql",
 "lua-cmsgpack",
 "djon",
 "gamecake-grd",
 "gamecake-wire",
 "gamecake-pack",
 "gamecake-fats",
 "gamecake-box2d",
 "gamecake-gles",
 "gamecake-al",
}
description={
 homepage="https://xriss.github.io/gamecake/docs/lua/",
 license="MIT",
 summary="A collection of modules from the gamecake project",
 detailed=[[

See https://github.com/xriss/gamecake for the source.

This pulls in as many dependencies as it can to try and mimic the 
modules that gamecake provides in a luarocks environment.

This is not a perfect copy but is reasonably close and is primarily 
used to share gamecake code with openresty.


 ]],
}
