
--module
local M={ modname=(...) } ; package.loaded[M.modname]=M


--[[#lua.wetgenes.gamecake.fun.entities

	fun_entities = require("wetgenes.gamecake.fun.entities")

Manage a simple structure to help group, update and draw discrete game objects.

This module contains only one function which can be used to create an entities
instance and the rest of this documentation concerns the return from this
create function, not the module

	entities = fun_entities.create()
	entities = fun_entities.create( { sortby={"first","second",...} } )
	
Create and return an entities object. A base object can be passed in and will
be filled in and returned. This can used to supply a sortby table to help
control the order of updates of different castes.

If passed in sortby is a table of [caste_name]=weight values to help control
the order of updates by caste and make it consistent. For instance you might
find it useful to force monsters to update before the player.

]]
M.create=function(entities)

	entities=entities or {} -- a place to store everything that needs to be updated
	
--[[#lua.wetgenes.gamecake.fun.entities.systems

	entities.systems={name=system,[1]=system}

A sorted table and lookup by caste name of each system. Table is sorted so it
will be traversed backwards, backwards traversal allows the current item to
delete itself.

]]
	entities.systems=entities.systems or {} -- global objects for each caste

--[[#lua.wetgenes.gamecake.fun.entities.uids

	entities.uids={[uid]=item,...}

A map of currently remembered uids to items.

]]
	entities.uid=(os.time()*0x10000)%0x100000000
	entities.uids=setmetatable({}, { __mode = 'v' }) -- weak values

--[[#lua.wetgenes.gamecake.fun.entities.generate_uid

	local uid = entities.generate_uid()

Create a "reasonably" unique id number and return it. we are only expecting
uniqueness within this program but we will probably be OK with other ids
provided they are not generated by a program starting at exactly the same time.
These are very simple time based uids that offer no security.

The point of uids is so we can refer to and lazy link items as weak values
making it easy to delete an item without worrying too much about where it has
been used. So instead of putting the item table inside another item table we
can use a uid reference instead.

Good for serialising data as well.

]]
	entities.generate_uid=function()
		entities.uid=(entities.uid+1)%0x100000000 -- we have 64k ids before we hit the next second
		return entities.uid
	end


--[[#lua.wetgenes.gamecake.fun.entities.remember_uid

	local it = entities.remember_uid( {} )

Remember an item in the uids table, generating a uid and setting it.uid to this
value if one does not already exist.

]]
	entities.remember_uid=function(it)
		it.uid=it.uid or entities.generate_uid()
		entities.uids[it.uid]=it
		return it
	end


--[[#lua.wetgenes.gamecake.fun.entities.forget_uid

	local it = entities.forget_uid( {uid=uid} )

Remove the item from the map of uids. Returns the item or nil if uid was
invalid unset or our map was not pointing to the correct item.

	local it = entities.forget_uid( entities.find_uid( uid ) )

Chain with find_uid to forget an item by uid and this is safe even if the item
does not exist.

]]
	entities.forget_uid=function(it)
		if not it then return nil end
		if not it.uid then return nil end
		if entities.uids[it.uid]~=it then return nil end  -- bad item lookup
		entities.uids[it.uid]=nil -- remove
		return it
	end

--[[#lua.wetgenes.gamecake.fun.entities.find_uid

	local it = entities.find_uid( uid )

Return the item with the given uid or nil if no such item has been remembered.

]]
	entities.find_uid=function(uid)
		return entities.uids[uid]
	end


--[[#lua.wetgenes.gamecake.fun.entities.systems.remove

	system = entities.systems.remove(caste)

Remove and return the system of the given caste.

]]
	entities.systems.remove=function(caste)
		entities.systems[caste]=nil
		for i,v in ipairs(entities.systems) do
			if v.caste==caste then
				return table.remove(entities.systems,i)
			end
		end
	end
	

--[[#lua.wetgenes.gamecake.fun.entities.systems.insert

	entities.systems.insert(system)

Insert a new system replacing any system of the same caste. system.caste should
be set to the caste of the system for this to work. As we also keep some
functions in this table, the names "insert", "remove" and "call" are not
available as caste names.

]]
	entities.systems.insert=function(it)
		entities.remember_uid(it)
		if it.caste then
			for i,v in ipairs(entities.systems) do
				if v.caste==it.caste then -- replace
					entities.systems[i]=it
					entities.systems[it.caste]=it
					return
				end
			end
			entities.systems[it.caste]=it
		end
		entities.systems[#entities.systems+1]=it
		table.sort(entities.systems,function(a,b)
			local av=entities.sortby[ a.caste ] or math.huge -- use caste to get sortby weight
			local bv=entities.sortby[ b.caste ] or math.huge -- put items without a weight last
			return ( av > bv ) -- sort backwards
		end)
	end


--[[#lua.wetgenes.gamecake.fun.entities.systems.call

	entities.systems.call(fname,...)

For every system call the function called fname like so.

	system[fname](system,...)

Returns the number of calls made, which will be the number of systems that had
an fname function to call.

]]
	entities.systems.call=function(fname,...)
		local count=0
		for i=#entities.systems,1,-1 do -- call backwards so item can remove self
			local system=entities.systems[i]
			if system[fname] then
				system[fname](system,...)
				count=count+1
			end
		end
		return count -- number of systems called
	end


	entities.sortby=entities.sortby or {} -- custom sort weights for update/draw order of each caste


--[[#lua.wetgenes.gamecake.fun.entities.sortby_update

	entities.sortby_update()

A function that takes the array part of entities.sortby and reverses the
key=value so a simple order list can be provided without any explicit weights.
The first caste name in the array gets a weight of 1, second 2 and so on.

]]
	entities.sortby_update=function()
		for i,v in ipairs(entities.sortby) do entities.sortby[v]=i end
	end
	entities.sortby_update()


--[[#lua.wetgenes.gamecake.fun.entities.reset

	entities.reset()
	
Empty the list of entities to update and draw, this does not reset the systems
table that should be modified with the insert and remove functions.

]]
	entities.reset=function()
--		entities.call(function(it) entities.remove(it) end) -- make sure things are removed?
		entities.info={} -- general data
		entities.data={} -- main lists of entities
		return entities
	end


--[[#lua.wetgenes.gamecake.fun.entities.caste

	entities.caste(caste)

Get the list of entities of a given caste, eg "bullets" or "enemies"

This list will be created if it does not already exist.

entities.sortby is used to keep this list in order.

]]
	entities.caste=function(caste)
		caste=caste or "generic"
		if not entities.data[caste] then -- create on use
			local items={}
			entities.data[caste]=items
			entities.data[#entities.data+1]=items
			table.sort(entities.data,function(a,b)
				local av=entities.sortby[ a.caste ] or math.huge -- get caste then use caste to get sortby weight
				local bv=entities.sortby[ b.caste ] or math.huge -- put items without a weight last
				return ( av > bv )
			end)
		end
		return entities.data[caste]
	end


--[[#lua.wetgenes.gamecake.fun.entities.add

	entities.add(it,caste)
	entities.add(it)

Add a new entity of caste or it.caste to the list of things to update.

]]
	entities.add=function(it,caste)
		entities.remember_uid(it)
		caste=caste or it.caste -- probably from item
		caste=caste or "generic"
		it.caste=caste
		local items=entities.caste(caste)
		items[ #items+1 ]=it -- add to end of array
		return it
	end


--[[#lua.wetgenes.gamecake.fun.entities.remove

	entities.remove(it)

Remove this entity, this is slightly expensive as we need to search in a table
to find it before calling table.remove which then has to shuffle the table to
fill in the hole.

With very dynamic items it can be faster to allocate all the items you need at
the start and then flag them on/off rather than add and remove dynamically.

It may make more sense to create an entity which handles its own list of
objects, such as particles. Then only use the entity system to keep track of a
master particles item that contains many particles and can add/remove/recycle
as it sees fit.

]]
	entities.remove=function(it)
		entities.forget_uid(it)
		local items=entities.caste(it.caste)
		for idx=#items,1,-1 do -- search backwards
			if items[idx]==it then
				table.remove(items,idx)
				return it
			end
		end	
	end


--[[#lua.wetgenes.gamecake.fun.entities.call

	entities.call(fname,...)

If fname is a string then that method will be invoked for every item where it
exists like so.

	if it[fname] then it[fname](it,...) end
	
if fname is a function then it will result in every item geting called with
that function like so.

	fname(it,...)

The calls are always made backwards through the table so that an item can
choose to delete itself.

Finally we return the number of calls we made so you can keep track of
currently active items.

]]
	entities.call=function(fname,...)
		local count=0
		if type(fname)=="function" then
			for i=#entities.data,1,-1 do
				local items=entities.data[i]
				for idx=#items,1,-1 do -- call backwards so item can remove self
					local it=items[idx]
					fname(it,...) -- call an explicit function
					count=count+1
				end	
			end
		else
			for i=#entities.data,1,-1 do
				local items=entities.data[i]
				for idx=#items,1,-1 do -- call backwards so item can remove self
					local it=items[idx]
					if it[fname] then -- call a method, if it exists
						it[fname](it,...)
						count=count+1
					end
				end
			end
		end
		return count -- number of items called
	end


--[[#lua.wetgenes.gamecake.fun.entities.get

	entities.get(name)

get a value previously saved, this is an easy way to find a unique entity, eg
the global space but it can be used to save any values you wish not just to
bookmark unique entities.

]]
	entities.get=function(name)
		return entities.info[name]
	end


--[[#lua.wetgenes.gamecake.fun.entities.set

	entities.set(name,value)

save a value by a unique name

]]
	entities.set=function(name,value)
		entities.info[name]=value
		return value
	end


--[[#lua.wetgenes.gamecake.fun.entities.manifest

	entities.manifest(name,value)

get a value previously saved, or initalize it to the given value if it does not
already exist. The default value is {} as this is intended for lists.

]]
	entities.manifest=function(name,empty)
		if not entities.info[name] then
			entities.info[name]=empty or {} -- create empty
		end
		return entities.info[name]
	end


-- reset and return the entities, creating the initial data and info tables
	return entities.reset()

end
