# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

	config.vm.box = "http://files.dryga.com/boxes/osx-yosemite-0.2.1.box"

# Use NFS for the shared folder

	config.vm.network "private_network", ip: "10.42.23.23"

	config.nfs.map_uid = Process.uid
	config.nfs.map_gid = Process.gid

	config.vm.synced_folder "../", "/gamecake",
		id: "gamecake",
		:nfs => true,
		:mount_options => ['nolock','vers=3','udp','noatime','dmode=777','fmode=777'],
		:linux__nfs_options => ['rw','async','insecure','no_subtree_check','no_acl','all_squash']

# the above works but owners are bad and seemingly hard to fix, so we hack around that



	config.vm.provision :shell, :path => "provision.sh"

end
