# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

#	config.vm.box = "http://files.dryga.com/boxes/osx-yosemite-0.2.1.box"
	config.vm.box = "https://vagrant-osx.nyc3.digitaloceanspaces.com/osx-sierra-0.3.1.box"

config.vm.provider "virtualbox" do |vb|
    # Fix "hfs mounted macintosh hd on device root_device" issue
    vb.customize ["modifyvm", :id, "--cpuidset", "1","000206a7","02100800","1fbae3bf","bfebfbff"]

    # Some more hacks for device recognition
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
    #vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC", "1"]
end

# Use NFS for the shared folder

	config.vm.network "private_network", ip: "10.42.23.23"

#	config.nfs.map_uid = Process.uid
#	config.nfs.map_gid = Process.gid

	config.vm.synced_folder "../", "/gamecake", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp,noatime']

# the above works but owners are bad and seemingly hard to fix, so we hack around that



	config.vm.provision :shell, :path => "provision.sh"

end
