
project "lib_wolfssl"
language "C"


includedirs { ".", "git", }

files{
--	"git/src/bio.c",
--	"git/src/conf.c",
	"git/src/crl.c",
--	"git/src/dtls13.c",
--	"git/src/dtls.c",
	"git/src/internal.c",
	"git/src/keys.c",
	"git/src/ocsp.c",
--	"git/src/pk.c",
--	"git/src/pk_ec.c",
--	"git/src/pk_rsa.c",
--	"git/src/quic.c",
	"git/src/sniffer.c",
--	"git/src/ssl_api_cert.c",
--	"git/src/ssl_api_crl_ocsp.c",
--	"git/src/ssl_api_dtls.c",
--	"git/src/ssl_api_ext.c",
--	"git/src/ssl_api_hs.c",
--	"git/src/ssl_api_pk.c",
--	"git/src/ssl_api_rw.c",
--	"git/src/ssl_asn1.c",
--	"git/src/ssl_bn.c",
	"git/src/ssl.c",
--	"git/src/ssl_certman.c",
--	"git/src/ssl_crypto.c",
--	"git/src/ssl_ech.c",
--	"git/src/ssl_err.c",
--	"git/src/ssl_load.c",
--	"git/src/ssl_misc.c",
--	"git/src/ssl_p7p12.c",
--	"git/src/ssl_sess.c",
--	"git/src/ssl_sk.c",
--	"git/src/ssl_tsp.c",
	"git/src/tls13.c",
	"git/src/tls.c",
	"git/src/wolfio.c",
--	"git/src/x509.c",
--	"git/src/x509_str.c",
}

files{
	"git/wolfcrypt/src/aes.c",
	"git/wolfcrypt/src/arc4.c",
--	"git/wolfcrypt/src/ascon.c",
	"git/wolfcrypt/src/asm.c",
	"git/wolfcrypt/src/asn.c",
--	"git/wolfcrypt/src/asn_orig.c",
--	"git/wolfcrypt/src/asn_tsp.c",
--	"git/wolfcrypt/src/async.c",
	"git/wolfcrypt/src/blake2b.c",
	"git/wolfcrypt/src/blake2s.c",
	"git/wolfcrypt/src/camellia.c",
	"git/wolfcrypt/src/chacha20_poly1305.c",
	"git/wolfcrypt/src/chacha.c",
	"git/wolfcrypt/src/cmac.c",
	"git/wolfcrypt/src/coding.c",
	"git/wolfcrypt/src/compress.c",
	"git/wolfcrypt/src/cpuid.c",
	"git/wolfcrypt/src/cryptocb.c",
	"git/wolfcrypt/src/curve25519.c",
	"git/wolfcrypt/src/curve448.c",
	"git/wolfcrypt/src/des3.c",
	"git/wolfcrypt/src/dh.c",
	"git/wolfcrypt/src/dsa.c",
	"git/wolfcrypt/src/ecc.c",
	"git/wolfcrypt/src/ecc_fp.c",
	"git/wolfcrypt/src/eccsi.c",
	"git/wolfcrypt/src/ed25519.c",
	"git/wolfcrypt/src/ed448.c",
	"git/wolfcrypt/src/error.c",
--	"git/wolfcrypt/src/evp.c",
--	"git/wolfcrypt/src/evp_pk.c",
	"git/wolfcrypt/src/falcon.c",
	"git/wolfcrypt/src/fe_448.c",
	"git/wolfcrypt/src/fe_low_mem.c",
	"git/wolfcrypt/src/fe_operations.c",
	"git/wolfcrypt/src/ge_448.c",
	"git/wolfcrypt/src/ge_low_mem.c",
	"git/wolfcrypt/src/ge_operations.c",
	"git/wolfcrypt/src/hash.c",
	"git/wolfcrypt/src/hmac.c",
--	"git/wolfcrypt/src/hpke.c",
	"git/wolfcrypt/src/integer.c",
	"git/wolfcrypt/src/kdf.c",
	"git/wolfcrypt/src/logging.c",
	"git/wolfcrypt/src/md2.c",
	"git/wolfcrypt/src/md4.c",
	"git/wolfcrypt/src/md5.c",
	"git/wolfcrypt/src/memory.c",
--	"git/wolfcrypt/src/misc.c",
	"git/wolfcrypt/src/pkcs12.c",
	"git/wolfcrypt/src/pkcs7.c",
	"git/wolfcrypt/src/poly1305.c",
--	"git/wolfcrypt/src/puf.c",
	"git/wolfcrypt/src/pwdbased.c",
	"git/wolfcrypt/src/random.c",
	"git/wolfcrypt/src/rc2.c",
	"git/wolfcrypt/src/ripemd.c",
--	"git/wolfcrypt/src/rng_bank.c",
	"git/wolfcrypt/src/rsa.c",
	"git/wolfcrypt/src/sakke.c",
	"git/wolfcrypt/src/sha256.c",
	"git/wolfcrypt/src/sha3.c",
	"git/wolfcrypt/src/sha512.c",
	"git/wolfcrypt/src/sha.c",
	"git/wolfcrypt/src/signature.c",
	"git/wolfcrypt/src/siphash.c",
--	"git/wolfcrypt/src/sm2.c",
--	"git/wolfcrypt/src/sm3.c",
--	"git/wolfcrypt/src/sm4.c",
	"git/wolfcrypt/src/sp_arm32.c",
	"git/wolfcrypt/src/sp_arm64.c",
	"git/wolfcrypt/src/sp_armthumb.c",
	"git/wolfcrypt/src/sp_c32.c",
	"git/wolfcrypt/src/sp_c64.c",
	"git/wolfcrypt/src/sp_cortexm.c",
	"git/wolfcrypt/src/sp_dsp32.c",
	"git/wolfcrypt/src/sp_int.c",
--	"git/wolfcrypt/src/sp_sm2_arm32.c",
--	"git/wolfcrypt/src/sp_sm2_arm64.c",
--	"git/wolfcrypt/src/sp_sm2_armthumb.c",
--	"git/wolfcrypt/src/sp_sm2_c32.c",
--	"git/wolfcrypt/src/sp_sm2_c64.c",
--	"git/wolfcrypt/src/sp_sm2_cortexm.c",
--	"git/wolfcrypt/src/sp_sm2_x86_64.c",
	"git/wolfcrypt/src/sp_x86_64.c",
	"git/wolfcrypt/src/srp.c",
	"git/wolfcrypt/src/tfm.c",
--	"git/wolfcrypt/src/tsp.c",
	"git/wolfcrypt/src/wc_dsp.c",
	"git/wolfcrypt/src/wc_encrypt.c",
--	"git/wolfcrypt/src/wc_frodokem.c",
--	"git/wolfcrypt/src/wc_frodokem_mat.c",
--	"git/wolfcrypt/src/wc_lms.c",
--	"git/wolfcrypt/src/wc_lms_impl.c",
--	"git/wolfcrypt/src/wc_mldsa.c",
--	"git/wolfcrypt/src/wc_mlkem.c",
--	"git/wolfcrypt/src/wc_mlkem_poly.c",
	"git/wolfcrypt/src/wc_pkcs11.c",
	"git/wolfcrypt/src/wc_port.c",
--	"git/wolfcrypt/src/wc_she.c",
--	"git/wolfcrypt/src/wc_slhdsa.c",
--	"git/wolfcrypt/src/wc_xmss.c",
--	"git/wolfcrypt/src/wc_xmss_impl.c",
--	"git/wolfcrypt/src/wolfentropy.c",
	"git/wolfcrypt/src/wolfevent.c",
	"git/wolfcrypt/src/wolfmath.c",
}

-- newer
--[[
files{
--	"git/src/bio.c",
--	"git/src/conf.c",
	"git/src/crl.c",
	"git/src/dtls13.c",
	"git/src/dtls.c",
	"git/src/internal.c",
	"git/src/keys.c",
	"git/src/ocsp.c",
--	"git/src/pk.c",
--	"git/src/pk_ec.c",
--	"git/src/pk_rsa.c",
	"git/src/quic.c",
	"git/src/sniffer.c",
--	"git/src/ssl_api_cert.c",
--	"git/src/ssl_api_crl_ocsp.c",
--	"git/src/ssl_api_dtls.c",
--	"git/src/ssl_api_ext.c",
--	"git/src/ssl_api_hs.c",
--	"git/src/ssl_api_pk.c",
--	"git/src/ssl_api_rw.c",
--	"git/src/ssl_asn1.c",
--	"git/src/ssl_bn.c",
	"git/src/ssl.c",
--	"git/src/ssl_certman.c",
--	"git/src/ssl_crypto.c",
--	"git/src/ssl_ech.c",
--	"git/src/ssl_err.c",
--	"git/src/ssl_load.c",
--	"git/src/ssl_misc.c",
--	"git/src/ssl_p7p12.c",
--	"git/src/ssl_sess.c",
--	"git/src/ssl_sk.c",
--	"git/src/ssl_tsp.c",
	"git/src/tls13.c",
	"git/src/tls.c",
	"git/src/wolfio.c",
--	"git/src/x509.c",
--	"git/src/x509_str.c",
}

files{
	"git/wolfcrypt/src/aes.c",
	"git/wolfcrypt/src/arc4.c",
	"git/wolfcrypt/src/ascon.c",
	"git/wolfcrypt/src/asm.c",
	"git/wolfcrypt/src/asn.c",
--	"git/wolfcrypt/src/asn_orig.c",
--	"git/wolfcrypt/src/asn_tsp.c",
	"git/wolfcrypt/src/async.c",
	"git/wolfcrypt/src/blake2b.c",
	"git/wolfcrypt/src/blake2s.c",
	"git/wolfcrypt/src/camellia.c",
	"git/wolfcrypt/src/chacha20_poly1305.c",
	"git/wolfcrypt/src/chacha.c",
	"git/wolfcrypt/src/cmac.c",
	"git/wolfcrypt/src/coding.c",
	"git/wolfcrypt/src/compress.c",
	"git/wolfcrypt/src/cpuid.c",
	"git/wolfcrypt/src/cryptocb.c",
	"git/wolfcrypt/src/curve25519.c",
	"git/wolfcrypt/src/curve448.c",
	"git/wolfcrypt/src/des3.c",
	"git/wolfcrypt/src/dh.c",
	"git/wolfcrypt/src/dsa.c",
	"git/wolfcrypt/src/ecc.c",
	"git/wolfcrypt/src/ecc_fp.c",
	"git/wolfcrypt/src/eccsi.c",
	"git/wolfcrypt/src/ed25519.c",
	"git/wolfcrypt/src/ed448.c",
	"git/wolfcrypt/src/error.c",
--	"git/wolfcrypt/src/evp.c",
--	"git/wolfcrypt/src/evp_pk.c",
	"git/wolfcrypt/src/falcon.c",
	"git/wolfcrypt/src/fe_448.c",
	"git/wolfcrypt/src/fe_low_mem.c",
	"git/wolfcrypt/src/fe_operations.c",
	"git/wolfcrypt/src/ge_448.c",
	"git/wolfcrypt/src/ge_low_mem.c",
	"git/wolfcrypt/src/ge_operations.c",
	"git/wolfcrypt/src/hash.c",
	"git/wolfcrypt/src/hmac.c",
	"git/wolfcrypt/src/hpke.c",
	"git/wolfcrypt/src/integer.c",
	"git/wolfcrypt/src/kdf.c",
	"git/wolfcrypt/src/logging.c",
	"git/wolfcrypt/src/md2.c",
	"git/wolfcrypt/src/md4.c",
	"git/wolfcrypt/src/md5.c",
	"git/wolfcrypt/src/memory.c",
--	"git/wolfcrypt/src/misc.c",
	"git/wolfcrypt/src/pkcs12.c",
	"git/wolfcrypt/src/pkcs7.c",
	"git/wolfcrypt/src/poly1305.c",
	"git/wolfcrypt/src/puf.c",
	"git/wolfcrypt/src/pwdbased.c",
	"git/wolfcrypt/src/random.c",
	"git/wolfcrypt/src/rc2.c",
	"git/wolfcrypt/src/ripemd.c",
	"git/wolfcrypt/src/rng_bank.c",
	"git/wolfcrypt/src/rsa.c",
	"git/wolfcrypt/src/sakke.c",
	"git/wolfcrypt/src/sha256.c",
	"git/wolfcrypt/src/sha3.c",
	"git/wolfcrypt/src/sha512.c",
	"git/wolfcrypt/src/sha.c",
	"git/wolfcrypt/src/signature.c",
	"git/wolfcrypt/src/siphash.c",
	"git/wolfcrypt/src/sm2.c",
	"git/wolfcrypt/src/sm3.c",
	"git/wolfcrypt/src/sm4.c",
	"git/wolfcrypt/src/sp_arm32.c",
	"git/wolfcrypt/src/sp_arm64.c",
	"git/wolfcrypt/src/sp_armthumb.c",
	"git/wolfcrypt/src/sp_c32.c",
	"git/wolfcrypt/src/sp_c64.c",
	"git/wolfcrypt/src/sp_cortexm.c",
	"git/wolfcrypt/src/sp_dsp32.c",
	"git/wolfcrypt/src/sp_int.c",
	"git/wolfcrypt/src/sp_sm2_arm32.c",
	"git/wolfcrypt/src/sp_sm2_arm64.c",
	"git/wolfcrypt/src/sp_sm2_armthumb.c",
	"git/wolfcrypt/src/sp_sm2_c32.c",
	"git/wolfcrypt/src/sp_sm2_c64.c",
	"git/wolfcrypt/src/sp_sm2_cortexm.c",
	"git/wolfcrypt/src/sp_sm2_x86_64.c",
	"git/wolfcrypt/src/sp_x86_64.c",
	"git/wolfcrypt/src/srp.c",
	"git/wolfcrypt/src/tfm.c",
	"git/wolfcrypt/src/tsp.c",
	"git/wolfcrypt/src/wc_dsp.c",
	"git/wolfcrypt/src/wc_encrypt.c",
	"git/wolfcrypt/src/wc_frodokem.c",
	"git/wolfcrypt/src/wc_frodokem_mat.c",
	"git/wolfcrypt/src/wc_lms.c",
	"git/wolfcrypt/src/wc_lms_impl.c",
	"git/wolfcrypt/src/wc_mldsa.c",
	"git/wolfcrypt/src/wc_mlkem.c",
	"git/wolfcrypt/src/wc_mlkem_poly.c",
	"git/wolfcrypt/src/wc_pkcs11.c",
	"git/wolfcrypt/src/wc_port.c",
	"git/wolfcrypt/src/wc_she.c",
	"git/wolfcrypt/src/wc_slhdsa.c",
	"git/wolfcrypt/src/wc_xmss.c",
	"git/wolfcrypt/src/wc_xmss_impl.c",
	"git/wolfcrypt/src/wolfentropy.c",
	"git/wolfcrypt/src/wolfevent.c",
	"git/wolfcrypt/src/wolfmath.c",
}
]]

defines{
	"HAVE_EX_DATA",
	"SESSION_CERTS",
	"HAVE_ALPN",
	"WOLFSSL_ALLOW_TLSV10",
	"WOLFSSL_CERT_GEN",
	"WOLFSSL_USER_SETTINGS",
	"OPENSSL_EXTRA",
	"OPENSSL_ALL",
--	"WOLFSSL_ALT_CERT_CHAINS",
--	"WOLFSSL_SYS_CA_CERTS",
--	"NO_FILESYSTEM",
}

	buildlinkoptions{
		"-Wno-implicit-function-declaration",
	}




if WINDOWS then

--	defines "USE_WINDOWS_API"
	defines "_WIN32_WINNT=0x0600"
--	defines "WINVER=0x0600"

	links { "ws2_32" }

end

configuration "Debug"
	defines{
		"DEBUG_WOLFSSL",
--		"WOLFSSL_LOGGINGENABLED_DEFAULT=0",
	}
configuration {}

KIND{}

