build={
 ["modules"]={
  ["wire.core"]={
   ["incdirs"]={
    "lua_wire",
   },
   ["sources"]={
    "lua_wire/code/lua_wire.c",
   },
  },
  ["wetgenes.string"]="lua_wire/code/wire.lua",
 },
 ["type"]="builtin",
}
dependencies={
 "bit32",
}
description={
 ["homepage"]="https://github.com/xriss/gamecake",
 ["license"]="MIT",
}
package="wolfsock"
source={
 ["url"]="/home/kriss/devcake/gamecake/rocks/wolfsock/src.zip",
}
version="26-260812"
