build={
 modules={
  wire="lua_wire/code/wire.lua",
  ["wire.core"]={
   incdirs={
    "lua_wire",
    "lua_wire/c11threads/git",
   },
   sources={
    "lua_wire/code/lua_wire.c",
   },
  },
  wiretasks="lua_wire/code/wiretasks.lua",
 },
 platform={
  windows={
   ["wire.core"]={
    sources={
     "lua_wire/code/lua_wire.c",
     "lua_wire/code/c11threads/git/c11threads_win32.c",
    },
   },
  },
 },
 type="builtin",
}
dependencies={
 "lua >= 5.1 <= 5.2",
}
description={
 homepage="https://xriss.github.io/gamecake/docs/lua.wire/",
 license="MIT",
}
