
project "lib_wolfssl"
language "C"


includedirs { "git", }

files{
	"git/src/**.c",
	"git/wolfcrypt/src/**.c",
}

defines{
	"OPENSSL_EXTRA",
	"OPENSSL_ALL",
	"HAVE_DH",
	"HAVE_EX_DATA",
	"HAVE_TLS_EXTENSIONS",
	"HAVE_AESGCM",
	"HAVE_ALPN",
	"HAVE_SHA512",
--	"HAVE_NULL_CIPHER",
	"SESSION_CERTS",
	"WOLFSSL_CERT_GEN",
	"WOLFSSL_ALLOW_TLSV10",
	"WOLFSSL_TLS12",
	"WOLFSSL_SHA512",
	"WOLFSSL_SHA384",
	"WOLFSSL_TLS13",
	"WC_RSA_PSS",
	"HAVE_FFDHE_2048",
	"HAVE_FFDHE_3072",
	"HAVE_FFDHE_4096",
	"HAVE_FFDHE_6144",
	"HAVE_FFDHE_8192",
	"HAVE_HKDF",
	"HAVE_SUPPORTED_CURVES",
	"WOLFSSL_ALT_CERT_CHAINS",
	"DEBUG_WOLFSSL",
}

KIND{}

