name: gamecake
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: a single exe cross platform game engine # 79 char long summary
description: |
  GameCake is a single exe cross platform game engine,
  a command line build of Lua(JIT) with embedded bindings to many libraries.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

#base: core18

parts:

  gamecake:

    plugin: make

    source: .

    override-build: |
      ./make --openal=sys --clean
      cp exe/gamecake.nix $SNAPCRAFT_PART_INSTALL/gamecake

    build-packages:
      - premake4
      - libluajit-5.1-dev
      - libsdl2-dev
      - libopenal-dev

    stage-packages:
      - libglu1-mesa
      - libgl1-mesa-dri

apps:

  gamecake:

    command: gamecake

    plugs:
      - home
      - x11
      - opengl
      - alsa
      - pulseaudio
      - network
      - joystick
      - hidraw

  grd:

    command: gamecake -lcmd -- grd

  midi:

    command: gamecake -lcmd -- midi


