name: gamecake
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: a single exe cross platform game engine # 79 char long summary
description: |
  GameCake is a single exe cross platform game engine,
  a command line build of Lua(JIT) with embedded bindings to many libraries.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core20

parts:

  desktop-glib-only:
  
    build-packages:
      - libglib2.0-dev
    
    plugin: make
    
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    
    source-subdir: glib-only
    
    stage-packages:
      - libglib2.0-bin


  alsa:
    plugin: nil

    source: https://github.com/diddledan/snapcraft-alsa.git

    override-pull: |
      cat > alsa.conf <<EOF
      pcm.!default {
        type pulse
        fallback "sysdefault"
        hint {
          show on
          description "Default ALSA Output (currently PulseAudio Sound Server)"
        }
      }
      ctl.!default {
        type pulse
        fallback "sysdefault"
      }
      EOF

    override-build: |
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc alsa.conf

    build-packages:
      - libasound2-dev

    stage-packages:
      - libasound2
      - libasound2-plugins

  gamecake:

    plugin: make

    source: .

    override-build: |
      ./make --openal=sys --clean
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp exe/gamecake.nix $SNAPCRAFT_PART_INSTALL/bin/gamecake
      cp gamecakejam $SNAPCRAFT_PART_INSTALL/bin/gamecakejam
      mkdir $SNAPCRAFT_PART_INSTALL/gamecakejam
      mkdir $SNAPCRAFT_PART_INSTALL/gamecakejam/cakes

    build-packages:
      - libluajit-5.1-dev
      - libsdl2-dev
      - libopenal-dev
      - luajit
      - lua-filesystem

    stage-packages:
      - libglu1-mesa
      - libgl1-mesa-dri
      - libasound2
      - libasyncns0
      - libflac8
      - libluajit-5.1-2
      - libogg0
      - libopenal1
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libsndio7.0
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1

    organize:
      usr/lib/*/pulseaudio/*: usr/lib/

    after:
      - desktop-glib-only
      - alsa

apps:

  gamecake:

    command: desktop-launch gamecake

    plugs:
      - home
      - x11
      - opengl
      - alsa
      - pulseaudio
      - network
      - joystick
      - hidraw
      - desktop
      - desktop-legacy
      - wayland
      - unity7

    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf

  grd:

    command: gamecake -lcmd -- grd

    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf

  midi:

    command: gamecake -lcmd -- midi

    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf


  jam:

    command: desktop-launch gamecakejam

    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf


plugs:
  cakes:
    interface: content
    target: $SNAP/gamecakejam/cakes
    default-provider: gamecakejam:cakes
