
[[enums]]
== Enums

Libusb enums are mapped in MoonUSB to sets of string literals (as is customary in Lua).

If needed, the following function can be used to obtain the list of literals admitted by 
a particular enum type.

[[usb.enum]]
* {_literal_} = *usb.enum*(_enumtype_) +
[small]#Returns a table listing the literals admitted by _enumtype_ (given as a string, e.g.
'_blendop_', '_format_', etc).#

Below is the list of the enum types and the literals they admit.

[[capability]]
[small]#*capability*: _libusb_capability_ +
Values: '_hotplug_', '_hid access_', '_detach kernel driver_'.#

[[class]]
[small]#*class*: USB class codes (see: https://www.usb.org/defined-class-codes). +
Values: '_per interface_', '_audio_', '_cdc_', '_hid_', '_physical_', '_image_', '_printer_', '_mass storage_', '_hub_', '_cdc data_', '_smart card_', '_content security_', '_video_', '_personal healthcare_', '_audio video_', '_billboard_', '_type c bridge_', '_diagnostic_', '_wireless_', '_miscellaneous_', '_application specific_', '_vendor specific_'.#

[[direction]]
[small]#*direction*: _libusb_endpoint_direction_ +
Values: '_out_', '_in_'.#

[[errcode]]
[small]#*errcode*: _libusb_error_, _libusb_transfer_status_ +
Values: '_success_', '_io error_', '_invalid param_', '_access_', '_no device_', '_not found_', '_busy_', '_timeout_', '_overflow_', '_pipe_', '_interrupted_', '_no mem_', '_not supported_', '_other_', '_success_', '_error_', '_timeout_', '_cancelled_', '_stall_', '_no device_', '_overflow_'.#

[[hotplugevent]]
[small]#*hotplugevent*: _libusb_hotplug_event + libusb_hotplug_flags_ +
Values: '_attached_', '_detached_'.#

[[isosynctype]]
[small]#*isosynctype*: _libusb_iso_sync_type_ +
Values: '_none_', '_async_', '_adaptive_', '_sync_'.#

[[isousagetype]]
[small]#*isousagetype*: _libusb_iso_usage_type_ +
Values: '_data_', '_feedback_', '_implicit_'.#

[[loglevel]]
[small]#*loglevel*: _libusb_log_level_ +
Values: '_none_', '_error_', '_warning_', '_info_', '_debug_'.#

[[option]]
[small]#*option*: _libusb_option_ +
Values: '_log level_', '_use usbdk_', '_weak authority_'.#

[[requestrecipient]]
[small]#*requestrecipient*: _libusb_request_recipient_ +
Values: '_device_', '_interface_', '_endpoint_', '_other_'.#

[[requesttype]]
[small]#*requesttype*: _libusb_request_type_ +
Values: '_standard_', '_class_', '_vendor_', '_reserved_'.#

[[speed]]
[small]#*speed*:  _libusb_speed_ +
Values: '_unknown_', '_low_', '_full_', '_high_', '_super_', '_super plus_'.#

[[standardrequest]]
[small]#*standardrequest*: _libusb_standard_request_ +
Values: '_get status_', '_clear feature_', '_set feature_', '_set address_', '_get descriptor_', '_set descriptor_', '_get configuration_', '_set configuration_', '_get interface_', '_set interface_', '_synch frame_', '_set sel_', '_set isoch delay_'.#

[[transfertype]]
[small]#*transfertype*: _libusb_endpoint_transfer_type_ +
Values: '_control_', '_isochronous_', '_bulk_', '_interrupt_'.#

[[transferstatus]]
[small]#*transferstatus*: _libusb_transfer_status_ +
Values: '_completed_', '_error_', '_timeout_', '_cancelled_', '_stall_', '_no device_', '_overflow_'.#

[[type]]
[small]#*type*: primitive type (char=8 bit, short=16 bit, int=32 bit, long=64 bit, float=32 bit, double=64 bit) +
Values: '_char_', '_uchar_', '_short_', '_ushort_', '_int_', '_uint_', '_long_', '_ulong_', '_float_', '_double_'.#

