
[[synchapi]]
== Synchronous I/O

[small]#Rfr: link:++http://libusb.sourceforge.net/api-1.0/group__libusb__synchio.html++[Synchronous device I//O].#

The functions listed in this section are blocking and return only when the requested transfer either completes or fails.
This means that they do not require an event loop (see <<polling, polling>>), but also that
they may block the application for long times, which may or may not be acceptable.
If it is not, then the <<asynchapi, asynchronous I/O>> API should be used instead.

* _transferred_ = <<devhandle, _devhandle_>>++:++*control_transfer*(_ptr_, _length_, _timeout_) +
[small]#Perform a USB control transfer and returns the number of bytes of data actually transferred. +
_ptr_: lightuserdata containing a pointer to at least _length_ bytes of contiguous memory, +
_timeout_: timeout in milliseconds (=0 for unlimited timeout). +
The first 8 bytes pointed to by _ptr_ must contain an encoded control setup packet, and the _length_
of the memory area must be at least 8 + _wLength_. +
The setup packet must be followed by the _wLength_ bytes of data to be transferred to the device, or
of space for the data to be received from the device. +
Rfr: _libusb_control_transfer( )_.#

* _transferred_ = <<devhandle, _devhandle_>>++:++*bulk_transfer*(_endpoint_, _ptr_, _length_, _timeout_) +
_transferred_ = <<devhandle, _devhandle_>>++:++*interrupt_transfer*(_endpoint_, _ptr_, _length_, _timeout_) +
[small]#Perform a USB bulk or interrupt transfer and returns the number of bytes of data actually transferred. +
_endpoint_: endpoint address, +
_ptr_: lightuserdata containing a pointer to at least _length_ bytes of contiguous memory, +
_timeout_: timeout in milliseconds (=0 for unlimited timeout). +
Rfr: _libusb_bulk_transfer( )_, _libusb_interrupt_transfer( )_.#

